### ISSUE TITLE
Add thread count customization 🔥

### ISSUE THREAD

**Issue by its5Q** [HapticX/happyx#100]
**Is your feature request related to a problem? Please describe.** 🤔
It would be great to be able to change the amount of threads that the web server is running with, when, for example, using httpbeast. Running everything in 1 thread isn't ideal, as, for example, some database operations can take time, slowing down the whole site.

**Describe the solution you'd like** 💡
An additional optional argument could be added in serve() for setting the amount of threads that the web server will run on.

**Comment by Ethosa** [comment]
> An additional optional argument could be added in serve() for setting the amount of threads that the web server will run on.

Maybe flag `-d:beastThread=NUMBER` is better solution?

**Comment by Ethosa** [comment]
Your issue can helpful for `httpx` also

https://github.com/ringabout/httpx/blob/master/src/httpx.nim#L156-L160

**Comment by Ethosa** [comment]
I'll add this flag to choose number of threads in next commit.
![image](https://github.com/HapticX/happyx/assets/49402667/e58e7634-4e6b-4819-90b5-44229219c5d5)
