### ISSUE TITLE
scripts not working for SPA? 🐛

### ISSUE THREAD

**Issue by quimt** [HapticX/happyx#107]
**Describe the bug** 🐛
Scripts appear to not be running for the 'first' time as the document and route load.

**To Reproduce** 👨‍🔬
try: 
```
    tScript(type="text/javascript"): """
      console.log("Hello, world!");
      """
```

**Expected behavior** 🤔
Script should run once as app loads. 

Instead nothing writes to the console.

If you use importjs to create a proc that does the same thing, then attach that to a button's `@click`  event, it works.

```
proc writeToConsole(s: cstring) {.importjs: "console.log(@)".}
...
    tButton:
      "test"
      @click:
        writeToConsole(s="success")

```
But it only works with the event of the button click. This, for instance, does not work:

```
    "/":
        writeToConsole(s="success")
```

**Comment by Ethosa** [comment]
I think that `tScript` is not working because it added to DOM after DOM parsed by browser.

instead of `tScript` you can use:

```nim
`template`:
  nim:
    # Nim code here ...
  "Hello, world"
```

You can also use procedures:
```nim
`template`:
  nim:
    writeToConsole(s="success")
  "Hello, world"
```

**Comment by quimt** [comment]
Alright, would still be good to get tScript working though since anyone would expect something producing <script> tags to work. 

I saw those nim blocks in the source, but evidently didn't read deeply enough to see that they are part of the API.!

This is working, and I see how the syntax might extend to `:js` or `:c` or other code injections in the future, but it looks like it will involve a bit of an extra learning curve, and maybe increase the time spent on debugging. Is what's outside of the `:nim` block not already nim?

I'm just thinking about procs and developer experience at the moment, but is there a benefit to the developer in doing it this way in the template and route environments, as opposed to trying to have the nim code run without being tagged by a `:nim` block?

```
`template`:
  # Nim code here ...
  "Hello, world"
  component SpecialButton:
   #Nim code can go here too?
```

**Comment by Ethosa** [comment]
> ... trying to have the nim code run without being tagged by a :nim block?

it's impossible at this moment. Nim code should be in `nim:` scope.

```nim
`template`:
  nim:
    # Nim code here ...
  "Hello, world"
  component SpecialButton:
    nim:
      #Nim code can go here too?
```
