### ISSUE TITLE
global post-render, other hooks 🔥

### ISSUE THREAD

**Issue by quimt** [HapticX/happyx#108]
Especially when embedding other apps into a SPA, one sometimes wants a global proc for housekeeping once the framework is 'done' with its turn.  This can spare the effort of having to have every possible affected component make the same request to the embedded app, and can allow some power to find a workaround if the embedded app is not behaving as expected.

More generally, hooks are a good tool for customization with other tools. What might become the analoguous tool with happyX? It's a little ambiguous at face value when a components ` 'script'` will run, but there will be use cases where we want _something_ running **before** the component template loads and _something else_ **after**. Currently, I understand that only one ` 'script'` block can be used in the definition of a component?

**Comment by Ethosa** [comment]
HappyX SPA supports these lifecycles:
`@created` - called once before component rendered.
`@updated` - called every fully HappyX app rerendered (HTML fully reloaded)
`@rendered` - called every component rerendered.
`@beforeUpdated` - called before every component rerendered.
`@exited` - called before page unload
`@pageShow` and `@pageHide` called on window pagehide/pageshow events

lifecycle usage:
```nim
component A:
  `template`:
    ...
  `script`:
    ...
  @updated:
    # nim code
  @created:
    # nim code
```

**Comment by Ethosa** [comment]
But list of lifecycles maybe extended

**Comment by quimt** [comment]
Would routes have lifecycles as well, or would it be restricted to the component type?

**Comment by Ethosa** [comment]
lifecycles supports only in components
