### ISSUE TITLE
self-consistency and scope with components 🐛

### ISSUE THREAD

**Issue by quimt** [HapticX/happyx#122]
We'd expect `self` to always refer to the same thing when declaring components, but this is not true. Sometimes `self` can't be accessed, or comes out as undefined. Sometimes, as in method calls, `self` comes out as type BaseComponent and is hence not ready for the component fields to be accessed.

Consider the following code:

```

component CTestChild:
  id: int
  color: cstring
  `template`:
    tDiv(style=fmt"color:{self.color}"):
      "subcomponent ID: {self.id}"

var ctest1 = use component CTestChild(id=1, color = "green")

component CTest:
  id: int
  newId: int = id + 1
  # testChild: CTestCHild = CTestChild(id = 44, color = "purple")
  ### won't compile
  # newId: cstring = fmt"newId: {id}"
  ### compiles but fails to render app
  message: cstring = ""
  `template`:
    tDiv: "template: {self.id} {self.newId}"
    tDiv: "message: {self.message}"
    tButton:
      "log id"
      @click:
        console.log(self.id)
    tButton:
      "get Id"
      @click:
        # self.message = fmt"{self.id}"
        ### won't compile
        # self.message = fmt"{CTest(self).getId()}"
        ### compiles but message is undefined
        self.message = fmt"{CTest(self).id}"
    component CTestChild(id = 3, color = "red")
    component CTestChild(id = self.id.val(), color = "blue") # undefined
    #component CTestChild(id = self.id, color = "blue") # same as above
    component ctest1 # compiles but causes weird duplications on rerender with above
  [methods]:
    proc getId(): int = self.id.val()

var test1 = use component CTest(id= 1)

appRoutes("ROOT"):
  "/":
    tDiv: component test1
    tDiv: component CTest(id = 7)


```

1.  It's inconsistent when one can use fields that have been declared to define new fields. Somewhat strangely, `self` cannot yet be used to refer to them, but they are part of the 'global' scope. However field values don't interact well with macros like `fmt` when defining a new field.
2. Methods apparently can't be called with self in @click assignments, but presumably break on the `js` end.
3. Sub-components apparently can't be initialiized with fields from self in the component template, nor can they be defined by default as a component field. This limits the ability to make modular code that limits the scope of rerenders, enhances code safety, or works in line with the `Nim`-ish philosophy of writing object oriented code that relies mostly on object composition as opposed to class inheritence.

- [x] `use component` rerender bug
- [x] `self.FIELD` as component param
- [x] `@click` scope
- [x] parameters calculating

**Comment by Ethosa** [comment]
> self comes out as type BaseComponent 
Yeap, it's known trouble

> newId: int = id + 1
stop stop stop ... it's works? 😳

**Comment by Ethosa** [comment]
> ```nim
> # newId: cstring = fmt"newId: {id}"
> ### compiles but fails to render app
> ```

It's not renders because it in proc params
![image](https://github.com/HapticX/happyx/assets/49402667/bd6a8989-f2d9-4c70-95d7-61cf2b2926ef)

**Comment by Ethosa** [comment]
> It's not renders because it in proc params

But I can try to move it into proc body 🤔

**Comment by Ethosa** [comment]
> component ctest1 # compiles but causes weird duplications on rerender with above

Yeap, I fixed it. In HappyX was call wrong render function.

**Comment by Ethosa** [comment]
```nim
tButton:
  "get Id"
  @click:
    # self.message = fmt"{self.id}"
    ### won't compile
    # self.message = fmt"{CTest(self).getId()}"
    ### compiles but message is undefined
    self.message = fmt"{CTest(self).id}"
```

![image](https://github.com/HapticX/happyx/assets/49402667/874ee910-54d1-4c20-9b05-43c554bb237b)

**Comment by Ethosa** [comment]
hmm ... it's works
![image](https://github.com/HapticX/happyx/assets/49402667/c7ef4c90-87eb-4391-8008-9423778e2aea)

**Comment by Ethosa** [comment]
This also works
![image](https://github.com/HapticX/happyx/assets/49402667/1b4ff1ce-0987-4178-9db6-491ff533ef40)

**Comment by Ethosa** [comment]
`self.val` also works
`self.get()` works
`self.getId()` works

**Comment by Ethosa** [comment]
Now it's renders and compiles
![image](https://github.com/HapticX/happyx/assets/49402667/784ba2f2-f52f-4156-b747-07eae7577264)

**Comment by quimt** [comment]
> hmm ... it's works ![image](https://user-images.githubusercontent.com/49402667/263506263-c7ef4c90-87eb-4391-8008-9423778e2aea.png)

For me  on Chrome   `component CTestChild(id = self.getId(), color = "blue")`  in the template compiles and renders but the blue component still displays as `undefined` in the child.

**Comment by quimt** [comment]
> Now it's renders and compiles ![image](https://user-images.githubusercontent.com/49402667/263507812-784ba2f2-f52f-4156-b747-07eae7577264.png)

FFor me on Chrome, the following compiles but does not render.:

```

component CTest:
  id: int
  newId: cstring = "newId: " & $id
  message: cstring = ""
  `template`:
    tDiv: "template: {self.id} {self.newId}"

var test1 = use component CTest(id= 1)

appRoutes("ROOT"):
  "/":
    tDiv: component test1
    tDiv: component CTest(id = 7)

```

I get 
![image](https://github.com/HapticX/happyx/assets/126020181/7b6a3e77-7a63-4dbb-95ab-3090dfa4fc6f)

**Comment by Ethosa** [comment]
update happyx to devel version
```nim
nimble install happyx@#head
```

**Comment by quimt** [comment]
> > It's not renders because it in proc params
> 
> But I can try to move it into proc body 🤔

Yeah, there is some general weirdness in the SPA DSL regarding `self` and the initproc params.  

- When declaring fields, use proc params
- When in the template, use fields of `self`
- In `@rendered` or `@created`, use proc params
- But in `@click`, even though it looks the same, use fields of `self`

It feels like too much switching for an efficient DSL. Also, it's hard to learn the switching patterns from the syntax of the DSL. The real reason why `@rendered` acts differently from `@click` is that one of these things is secretly declaring a component field. But that's an implementation detail that might change in the future, and that the SPA developer should not need to know in order to develop apps.

**Comment by Ethosa** [comment]
yeap but now you can use self anywhere :)

**Comment by quimt** [comment]
Cool, that will really help the API

**Comment by quimt** [comment]
> update happyx to devel version
> 
> ```nim
> nimble install happyx@#head
> ```

Switching to devel version. From now on I will be working with that branch.

**Comment by quimt** [comment]
> update happyx to devel version
> 
> ```nim
> nimble install happyx@#head
> ```

For component field declarations in @#head, only the last (uncommented) one works. The second compiles but `id` is not found iwhen the js is run.
```

  #newId: cstring = fmt"newId: {self.id}"
  ###newId: cstring = fmt"newId: {id}"
  #newId: cstring = "newId: " & $(self.id)
  newId: cstring = "newId: " & $id

```
