### ISSUE TITLE
how to define a model with generic

### ISSUE THREAD

**Issue by lost22git** [HapticX/happyx#131]
```nim
# compile failed here
model Result[T]:
  data: T 
  code: int
  errmsg: string
```

**Comment by Ethosa** [comment]
At this moment HappyX not provide request models with generic params

**Comment by Ethosa** [comment]
I'm not sure that generic models is need, because request models describes JSON/XML/x-www-form-urlencode/FormData structure

**Comment by Ethosa** [comment]
instead of request models you can use nim types
