### ISSUE TITLE
re2 dependency? 🐛

### ISSUE THREAD

**Issue by quimt** [HapticX/happyx#135]
On another machine with happyx v 2.9.0 installed, compilation gives an error stating that `re2` is not a valid identifier. Is there perhaps a new dependency that is not being checked?

**Comment by quimt** [comment]
Misread the subversion number. `hpx-v` yields `HappyX 2.9.2`

**Comment by Ethosa** [comment]
try to update to `happyx@#head`

**Comment by quimt** [comment]
Earlier yesterday this simply crashed. Now it reports an error:
`/tmp/nimble_11904/githubcom_HapticXhappyx_#head/src/happyx/hpx.nim.cfg(7, 2) Error: argument for command line option expected: '-t'
`
What about this new command-line option?

**Comment by Ethosa** [comment]
try again pls)

**Comment by quimt** [comment]
Still `undeclared identifier: 're2'`

**Comment by Ethosa** [comment]
try to update `nim-regex` to https://github.com/nitely/nim-regex/commit/199e696a1b0e0db72e2e5a657926e5b944e6ae2d 🤔

**Comment by quimt** [comment]
Installed with `nimble install regex@#head`. The latest commit is 199e696, so presumably the install to version `0.21.0` has that included?

**Comment by Ethosa** [comment]
what OS and Nim version you use?

**Comment by quimt** [comment]
Manjaro. Nim v.2.0.0

**Comment by Ethosa** [comment]
if it not helps for you, than delete REALLY ALL packages and reinstall their (or happyx only 🙂)

**Comment by Ethosa** [comment]
welcome to dependencies hell with nim2

**Comment by quimt** [comment]
I seem to have gotten it working
