### ISSUE TITLE
weird components behavior in nested for loops of SPA 🐛

### ISSUE THREAD

**Issue by quimt** [HapticX/happyx#139]
**Describe the bug** 🐛
Higher order loops seem to evaluate the inner loops first (then copy the results), which is not the usual behavior.

**To Reproduce** 👨‍🔬
Try something with `std/random`, for example:

```

component Num:
  n: int
  `template`:
    tSpan(style="margin-left:1em;"): " {self.n} "

randomize()

appRoutes("ROOT"):
  "/":
    for i in 1..3: tDiv:
      for j in 1..3:
        for k in 1..3:
          #component Num(i+j+k)
          #{i+j+k}
          #tSpan(style="margin-left: 1em"):  {rand(99)}
          component Num(rand(99))

```
![image](https://github.com/HapticX/happyx/assets/126020181/abf741de-5e88-44d3-8ab6-331e2578d8cd)

We'd normally expect no correlation, since 27 independent components would be created. The behavior is especially annoying since it seems to apply only to components: everything else gets executed each time we enter the inner loops.

**Comment by quimt** [comment]
This is probably due to the fact that components are placed in the DSL via a macro, while other parts of the syntax are handled more directly.

**Comment by Ethosa** [comment]
this problem only with components

**Comment by Ethosa** [comment]
![image](https://github.com/HapticX/happyx/assets/49402667/22b8650f-96e9-4c09-8f79-118d1a76c544)
![image](https://github.com/HapticX/happyx/assets/49402667/1a2aafd9-f93f-4669-98c6-853d1c75511c)

**Comment by Ethosa** [comment]
So now you can use it! 🙂
![image](https://github.com/HapticX/happyx/assets/49402667/f8db16b2-2568-4b5c-9095-34b5deb4b731)
![image](https://github.com/HapticX/happyx/assets/49402667/10469cac-900c-400d-8398-6f4945dd28c8)
