### ISSUE TITLE
subcomponents in template not unique 🐛

### ISSUE THREAD

**Issue by quimt** [HapticX/happyx#141]
**Describe the bug** 🐛
components created in the template of another component are being duplicated even if given different paramaters

**To Reproduce** 👨‍🔬
try more with arithmetic:
```

component Num:
  n: int
  `template`:
    tDiv: {self.n}

component NumSq:
  m: int
  `template`:
    tDiv: "{self.m} squared is: "
    component Num(self.m.val^2)

appRoutes("ROOT"):
  "/":
    component NumSq(5)
    component NumSq(3)


```
![image](https://github.com/HapticX/happyx/assets/126020181/f827ad7d-1f97-4173-8cb8-c574a9b58b9b)

**Comment by Ethosa** [comment]
Solved 🙂
![image](https://github.com/HapticX/happyx/assets/49402667/a9156f8a-5eea-4793-b620-376d06d02650)


Thanks to your help in finding bugs)

**Comment by quimt** [comment]
Likewise. Thanks for putting in a fix so quickly!
