### ISSUE TITLE
Liveview-like ?  🔥

### ISSUE THREAD

**Issue by jbjuin** [HapticX/happyx#142]
**Is your feature request related to a problem? Please describe.** 🤔
This is more an open question/discussion than a feature request :)

**Describe the solution you'd like** 💡

@Ethosa did you ever think about implementing something like Elixir Liveview feature with Happyx ?

I'm a python developer and used Django for more than 10 years and 3 years ago I stumbled on [django-reactor](https://github.com/edelvalle/reactor) which is a Liveview implementation for django. The code is very concise and easy to hack around (I keep using version 2.2.0b not master or version 3/4/5).  Django + django-reactor is really a strong tool to get the job done with "SPA" like application while writing almost only django code.

I've always wanted to try nim and never get the occasion but I have nonetheless alerts on news about Nim and I keep myself informed. 

As I understand it happyx has two "sides": one can choose to develop "for the backend" using a traditionnal request/response cycle sending back HTML to the browser or can choose to develop "for the frontend" with components written in Nim ? The communication between both being left to the developer.

So, my question is: did you think about writing "components" on the backend and communicate application state through websocket: send back HTML to the frontend on updates ? Maybe the dual js/c backends specific to nim could be used here to increase readibility and add Js capability to the frontend side of the component (which is not simple to do now using django-reactor for instance) ?

Anyway thank you for sharing your project Happyx ! Congratulation.

**Comment by Ethosa** [comment]
sounds like really good feature 🤔

**Comment by jbjuin** [comment]
Juste to give you some insights about using django reactor:

- one defines Components as python classes with Django (or jinja2) templates
- some specific html handlers are defined to add interactivity: `<button @click="click {'value': 42}">Click</button>`
- some specific methods receive events from the frontend: `def receive_click(self, value, *args, **kwargs)` 
- on event receive: the component HTML is re-rendered and pushed to the frontend using websocket
- the frontend uses Morphdom to update the HTML of the component and update only elements that changed

Drawbacks with reactor is that this is Django ! So scaling to large number of users may be an issue. The state of the application is stored in memory and there is a websocket connection per session so you have to be careful to not put too much data in the application state.

For private projects we developped some reactor helpers: a router (similar to vue), an app "store" (similar to vuex) to keep application state in a single place, etc.

**Comment by Ethosa** [comment]
Well now here is `route`, `js` and `html` methods and some "reactivity".

With liveviews in HappyX you'll can to user route path params, queries and etc that HappyX supports!

![image](https://github.com/HapticX/happyx/assets/49402667/c454e3da-d615-42e0-8872-b5299d8ef17f)
![image](https://github.com/HapticX/happyx/assets/49402667/08761c3a-2fc2-43c5-a238-73b33f7873b4)

**Comment by jbjuin** [comment]
@Ethosa hello. I'm just trying to start a test project with happyx. Do you have an example of nim code somewhere that uses the SSR components that you show as screenshots here ? I cannot find them neither in the documentation nor in the repository. I have difficulties figuring out how to lay out the files and code with this approach. Thanks !

**Comment by Ethosa** [comment]
yeap you can find example here:
https://github.com/HapticX/happyx/blob/master/tests/testc12.nim#L34-L46

**Comment by Ethosa** [comment]
documentation will update, but work is so slow

**Comment by jbjuin** [comment]
I bump on that error (using the file you pointed me to or the example you just gave in #164):
```
happyx/ssr/server.nim(1022, 24) Error: undeclared identifier: 'WebSocketClosedError'
candidates (edit distance, scope distance); see '--spellSuggest': 
 (6, 13): 'WebSocketError'
```

**Comment by Ethosa** [comment]
@jbjuin how you start server? which HTTP server is used?

**Comment by jbjuin** [comment]
Yes sorry here is the code:

```nim
import happyx

liveview:
  # This will on http://127.0.0.1:5000/
  "/":
    tDiv:
      tButton:
        "click server-side"
        @click:
          # this will executes at server side, here you can't use JS fetch
          # but you can work with db
          discard
      tButton(click = "someFunc"):
        "click client-side"
      tScript: """
        function someFunc(...) {
          ...
          // P.S. use extension for happyx for VS Code
        }
      """

mount InternalAPI:
  "/":
    # This will on http://127.0.0.1:5000/internal/
    # working with DB and return some data
    return 0

serve "127.0.0.1", 5000:
  mount "/internal" -> InternalAPI
```

and then

```sh
nim c -r ./main_components.nim
```

**Comment by Ethosa** [comment]
give me more information please, on my Windows machine this code works

**Comment by jbjuin** [comment]
Sure, nothing Fancy:

ubuntu: 20.04
nim: 2.0.0

```
nimble install happyx@#head
hpx create --name ssr_project --kind SSR
# choose Nim
cd ssr_project/src
nim c main.nim
```

and in main.nim:

```nim
import happyx

liveview:
  # This will on http://127.0.0.1:5000/
  "/":
    tDiv:
      tButton:
        "click server-side"
        @click:
          # this will executes at server side, here you can't use JS fetch
          # but you can work with db
          discard
      tButton(click = "someFunc"):
        "click client-side"
      tScript: """
        function someFunc(...) {
          ...
          // P.S. use extension for happyx for VS Code
        }
      """

mount InternalAPI:
  "/":
    # This will on http://127.0.0.1:5000/internal/
    # working with DB and return some data
    return 0

serve "127.0.0.1", 5000:
  mount "/internal" -> InternalAPI
```

Terminal output:

```
Hint: used config file '.choosenim/toolchains/nim-2.0.0/config/nim.cfg' [Conf]
Hint: used config file '.choosenim/toolchains/nim-2.0.0/config/config.nims' [Conf]
............................................................................................................................................................................................................................................................
ssr_project/src/main.nim(28, 1) template/generic instantiation of `serve` from here
ssr_project/src/main.nim(29, 3) template/generic instantiation of `routes` from here
.nimble/pkgs2/happyx-3.0.0-6c636148ba6185e09bfa387b3f573fd38f50987f/happyx/ssr/server.nim(811, 27) template/generic instantiation of `async` from here
.nimble/pkgs2/happyx-3.0.0-6c636148ba6185e09bfa387b3f573fd38f50987f/happyx/ssr/server.nim(1022, 24) Error: undeclared identifier: 'WebSocketClosedError'
candidates (edit distance, scope distance); see '--spellSuggest': 

```

Is that enough ?

**Comment by Ethosa** [comment]
Check your [`treeform/ws`](https://github.com/treeform/ws/releases/tag/0.5.0) version. It should be >= `0.5.0`

**Comment by jbjuin** [comment]
Ok I had a `ws` in `.nimble/pkgs` that was at `0.4.3` and one in `.nimble/pkgs2` that was at `0.5.0`. So this error is gone but I now have the following one:

```
Hint: used config file '.choosenim/toolchains/nim-2.0.0/config/nim.cfg' [Conf]
Hint: used config file '.choosenim/toolchains/nim-2.0.0/config/config.nims' [Conf]
............................................................................................................................................................................................................................................................
try_nim/ssr_project/src/main.nim(28, 1) template/generic instantiation of `serve` from here
try_nim/ssr_project/src/main.nim(29, 3) template/generic instantiation of `routes` from here
.nimble/pkgs2/happyx-3.0.0-6c636148ba6185e09bfa387b3f573fd38f50987f/happyx/ssr/server.nim(811, 27) template/generic instantiation of `async` from here
try_nim/ssr_project/src/main.nim(26, 12) Error: type mismatch
Expression: answer(req, 0)
  [1] req: Request
  [2] 0: int literal(0)

Expected one of (first mismatch at [position]):
[2] template answer(req: Request; message: string; code: HttpCode = Http200; headers: HttpHeaders = newHttpHeaders(
    [("Content-Type", "text/plain; charset=utf-8")]))

```

Any idea on that one ?

**Comment by Ethosa** [comment]
update to `#head` again)

**Comment by jbjuin** [comment]
Ok it compiles now (I removed all `pkgs/` and `pkgs2/` and installed happyx again) but I have the following error in the browser:

![happyx_ws_error](https://github.com/HapticX/happyx/assets/2361571/b69e26c7-d39a-4e6b-99ea-a1005baa8827)

When clicking the "server side" button: nothing happens. I guess is that the websocket is not opened...

**Comment by Ethosa** [comment]
> When clicking the "server side" button: nothing happens. I guess is that the websocket is not opened...

Yeap, because event is discard:
```nim

liveview:
  # This will on http://127.0.0.1:5000/
  "/":
    tDiv:
      tButton:
        "click server-side"
        @click:
          # this will executes at server side, here you can't use JS fetch
          # but you can work with db
          discard
```

**Comment by Ethosa** [comment]
> ![image](https://github.com/HapticX/happyx/assets/49402667/6946fdd7-4de1-40bf-b192-7c6858591917)

oh, I see

**Comment by Ethosa** [comment]
this is strange behavior 🤔

On Windows all works. I'll check it on ubuntu soon

**Comment by jbjuin** [comment]
Awesome ! I'm very new to nim so I do not have the good reflexes to debug even basic code. Thanks again !

**Comment by Ethosa** [comment]
So I run this code on `Ubuntu 22.04`, but ws connection was successfully connetced 🤔
![image](https://github.com/HapticX/happyx/assets/49402667/f9bd84d7-61d5-421d-83c4-2d73493d48cc)

**Comment by Ethosa** [comment]
I have no idea how to fix it.

@jbjuin  Which browser are you use?

**Comment by horanchikk** [comment]
@jbjuin All works on WSL Debian bro

Uname: Linux HOME-PC 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 GNU/Linux
Browser: ungoogled-chromium 117.0.5938.132

![image](https://github.com/HapticX/happyx/assets/46918417/764729dc-dac9-48f4-8600-8c4abc346332)

**Comment by horanchikk** [comment]
@Ethosa Tested on Firefox, it doesn't work with "ws://", need "wss://"

**Comment by ice-bergg** [comment]
Perhaps Electric in Clojure would be useful as an inspiration here, I think it's cutting edge tech for removing the server / client divide. Would be fantastic to see such a thing in Nim.

Their examples: https://electric.hyperfiddle.net/

**Comment by Ethosa** [comment]
@jbjuin @ice-bergg 
Upgraded liveviews now at `dev` branch:
```nim
import happyx

var counter = remember 0

liveview:
  "/":
    {counter}
    tButton:
      "click me!"
      @click:
        counter->inc()  # reactivity support

serve "127.0.0.1", 8000:
  discard
```
