### ISSUE TITLE
Need Documentation For ... 📕

### ISSUE THREAD

**Issue by MattStopa** [HapticX/happyx#146]
**Describe the information context** 💡
Which kind of documentation is missed?

I have been trying to use HappyX but I can't find any documentation on how it's really supposed to be used, nor how you prevent rerendering. Also... This is maybe a bug but the bug report requires more steps than getting top secret clearance in the CIA so I didn't file one.

Take this code below. It forces a redraw every single time. Okay, similar to react, but it also doesn't restore the focus to the input box, so how are you supposed to make this work exactly? I can't find anything in the docs or even the examples. 

Assigning any value makes the app not work, and then after doing this a few times the "Click Me" button disappears too... 

I'm so confused. I really like the idea of the framework but how to use it is another story

```# Import HappyX
import happyx

component Test: 
  someValue : string = "test"
  `template`: 
    tInput(type = "text", value=self.someValue)):
      @keyup(event) :
        self.someValue = $event.target.value
    tButton():
      "Click me"
    tDiv():
      {self.someValue}


# Declare component
component HelloWorld:
  `template`:
    component Test( )
```

**Additional context** ✌

**Comment by Ethosa** [comment]
At this moment you can do it this way :(
```nim
component Test: 
  someValue : string = "test"
  `template`: 
    tDiv:  # this is render bug, so you should put all tags in one root tag at now
      tInput(id = "test{self.uniqCompId}", type = "text", value=self.someValue):
        @keyup(event):
          self.someValue = $event.target.value  # Here component rerenders
          # Get current input and focus on it
          let inp = document.getElementById(fmt"test{self.uniqCompId}").InputElement
          inp.focus()
          inp.setSelectionRange(event.target.InputElement.selectionStart, event.target.InputElement.selectionEnd)
      tButton():
        "Click me"
      tDiv():
        {self.someValue}
```

**Comment by Ethosa** [comment]
In next commit to reproduce expected behavior you should just add id in input tag:
```nim
component Test: 
  someValue : string = "test"
  `template`:
    tDiv:
      tInput(id = "test", type = "text", value=self.someValue):
        @keyup(event):
          self.someValue = $event.target.value
      tButton():
        "Click me"
      tDiv():
        {self.someValue}
```
