### ISSUE TITLE
Exception on basic example

### ISSUE THREAD

**Issue by capocasa** [HapticX/happyx#147]
**Describe the bug** 🐛
Exception in basic example

**To Reproduce** 👨‍🔬
$ hpx create --name spa_project --kind SPA --path-params
$ cd spa_project
$ hpx dev --reload

An error was occurred when compiling main        
/home/carlo/.nimble/pkgs/regex-0.19.0/regex.nim(836, 29) template/generic instantiation from here
/home/carlo/.nimble/pkgs/regex-0.19.0/regex.nim(856, 18) Error: Exception can raise an unlisted exception: Exception

**Please complete the following information** 📃
HappyX 2.10.1
Arch Linux

**Comment by Ethosa** [comment]
please go to `spa_project/src` and run `nim js main`. Give me full error.

Also update regex to head `nimble install regex@#head`

**Comment by capocasa** [comment]
Sure!

```
Hint: used config file '/home/carlo/.choosenim/toolchains/nim-2.0.0/config/nim.cfg' [Conf]
Hint: used config file '/home/carlo/.choosenim/toolchains/nim-2.0.0/config/config.nims' [Conf]
Hint: used config file '/home/carlo/.config/nim/nim.cfg' [Conf]
..................................................................................................
/home/carlo/.nimble/pkgs/regex-0.19.0/regex.nim(836, 29) template/generic instantiation from here
/home/carlo/.nimble/pkgs/regex-0.19.0/regex.nim(856, 18) Error: Exception can raise an unlisted exception: Exception

```
after regex upgrade still uses 0.19 because it is pinned to specific commit in happyx.nimble.

**Comment by Ethosa** [comment]
so ... welcome to dependencies hell with nim2)
https://github.com/HapticX/happyx/issues/135

1. delete ALL `regex` and `happyx` packages from `.nimble/pkgs` and `.nimble/pkgs2`
2. reinstall it
3. successfull!

**Comment by Ethosa** [comment]
> after regex upgrade still uses 0.19 because it is pinned to specific commit in happyx.nimble.
yeap but nim2 with nimble say no

**Comment by capocasa** [comment]
I clobbered my .nimble directory and reinstalled 2.0.0 via choosenim- works fine now. That was it- thanks!
