### ISSUE TITLE
declared vars in SPA only modifiable in nim blocks

### ISSUE THREAD

**Issue by quimt** [HapticX/happyx#154]
**Describe the bug** 🐛
Variables can be freely declared in the SPA dsl, but only modified through `nim:` statements. Whether the var in question is `State[T]` or not is apparently irrelevant.

**Examine this code:** 👨‍🔬
```

var catStatus: string
var catLife: bool = false

if catLife:
  catStatus = "alive"
else:
  catStatus = "dead"

appRoutes("ROOT"):
  "/":
    tDiv: {catStatus}
    var dogStatus = "superposition"
    var dogLife: bool = false
    if dogLife:
      nim: dogStatus = "alive"
      #dogStatus = "alive"
    else:
      nim: dogStatus = "dead"
      # dogStatus = "dead"
    #dogStatus = "twisted"
    nim: dogStatus = "twisted"
    tDiv(style="color:red;"): {dogStatus}
    nim: console.log(fmt"dogstatus is {dogStatus}")


```

![image](https://github.com/HapticX/happyx/assets/126020181/920e95fd-0162-40f4-bd85-5bfe357fa7c6)

**Comment by Ethosa** [comment]
Now `nnkAsgn` used for assign tag attributes.

Here is two ways to solve issue:

1. new syntax for tag attributes (`:=` or something other) and `=` syntax for variables reassign
2. new syntax for variable reassign (`:=` or something other) and `=` for tag attrs

**Comment by Ethosa** [comment]
![image](https://github.com/HapticX/happyx/assets/49402667/b4a5952f-f1d7-4264-acf9-69ce1878fe54)

**Comment by Ethosa** [comment]
> 1. new syntax for tag attributes (:= or something other) and = syntax for variables reassign
> 2. new syntax for variable reassign (:= or something other) and = for tag attrs

well I think that first way is best solution

**Comment by quimt** [comment]
Yes I agree :

If you mean accessing the css attributes of a tag (or more generally a component), that's clearly a specialized (but very convenient) operation, distinct from variable assignment.
```

tDiv:
  color := red
  let val = rand(2)
  var dogStatus = "dead"
  if val == 1:
    dogStatus = "alive"
  {dogStatus}

```

> > 1. new syntax for tag attributes (:= or something other) and = syntax for variables reassign
> > 2. new syntax for variable reassign (:= or something other) and = for tag attrs
> 
> well I think that first way is best solution
