### ISSUE TITLE
hpx command not found 🐛

### ISSUE THREAD

**Issue by jbjuin** [HapticX/happyx#160]
**Describe the bug** 🐛
Following the README after `nimble install happyx@#head` I don't have the `hpx` command in my path

**To Reproduce** 👨‍🔬

```sh
cd my_project
nimble install happyx@#head
hpx create --name ssr_project --kind SSR
hpx command not found
```

**Expected behavior** 🤔
`hpx` command is present

**Please complete the following information** 📃
 - OS: linux ubuntu
 - OS Version: 20.04
 - HappyX version: head
 - HappyX project type [ssr/spa]: ssr
- nim: 2.0.0
- python: 3.11
 - HTTP Server (Default, Httpx, HttpBeast, MicroAsyncHttpServer): default

**Comment by Ethosa** [comment]
check that `.nimble/bin` in your PATH

**Comment by jbjuin** [comment]
That was it (and fast :) ) ! Thanks
