### ISSUE TITLE
New Feature 🔥: PWA by default

### ISSUE THREAD

**Issue by imxade** [HapticX/happyx#165]
**Is your feature request related to a problem? Please describe.** 🤔
No

**Describe the Feature** 💡
This feature request aims to introduce user-configurable options for PWAs. These options include:

- Progressive Web App (PWA) support (enabled by default)
  > If enabled, prompt for manifest.json
  - Offline access (from the cache and refresh upon reconnection)
  - enable widgets (for every route by default)

**Why?**
For an app like experience

**Comment by Ethosa** [comment]
![image](https://github.com/HapticX/happyx/assets/49402667/f90bc44c-3b55-41a0-b319-8e23bb57e1cd)
