### ISSUE TITLE
How to use htmx for a SSR app 🔥

### ISSUE THREAD

**Issue by jerrygzy** [HapticX/happyx#168]
**Is your feature request related to a problem? Please describe.** 🤔
I am trying to use [htmx](https://htmx.org/) for a SSR project, there is a old [example](https://arhamjain.com/2021/11/22/nim-simple-chat.html) using karax, since happyx is not using karax, what is the right way of using htmx in my project?

**Describe the solution you'd like** 💡
A tutorial for the happyx [documentation](https://hapticx.github.io/happyx/#/guide/)  will be great.

**Comment by Ethosa** [comment]
How I can see, you just need to import it via `unpkg`
![image](https://github.com/HapticX/happyx/assets/49402667/2aa10885-ac84-48ea-8256-fa3c2655991a)

Here two ways to use it with `SSR`:
1. Use it with [`nimja`](https://github.com/enthus1ast/nimja) template engine ([Docs](https://hapticx.github.io/happyx/happyx/tmpl_engine/engine.html))
  ```nim
  serve ...:
    get "/":
      # something code here
      return buildHtml
  ```
2. Use it with just `return buildHtml`:
  ```nim
  serve ...:
    get "/":
      # something code here
      return buildHtml:  # or other variable that contains builded HTML
        tHtml:
          tHead:
            ...
          tBody:
            ...
  ```

**Comment by jerrygzy** [comment]
Thanks for the reply, just got some basics working, 

when I Use it with [nimja](https://github.com/enthus1ast/nimja) template engine ([Docs](https://hapticx.github.io/happyx/happyx/tmpl_engine/engine.html))

`hpx create --name:htmx_example --kind:SSR`

edit the index.html file

```
<!DOCTYPE html><html>
  <head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <script src="https://unpkg.com/htmx.org@1.9.6"></script>
  </head>
  <body>
    You at {{ title }} page ✨
    <button
    hx-get="https://v2.jokeapi.dev/joke/Any?format=txt&safe-mode"
    hx-target="#output"
    >Click for Joke</button>
  
    <p id="output"></p>
  </body>
</html>
```

run `nim c -r ./src/main.nim` 

it works now, but the page looks very ugly, how can I use [tailwindcss](https://tailwindcss.com/) with happyx?

**Comment by Ethosa** [comment]
> it works now, but the page looks very ugly, how can I use [tailwindcss](https://tailwindcss.com/) with happyx?

You can use it now via cdn. I think about usage without cdn later.

**Comment by Ethosa** [comment]
In theory, you can do this way:
```shell
hpx create --name:htmx_example --kind:SSR --templates
cd htmx_example
npm init
npm install -D tailwindcss
npx tailwindcss init
```

After this you should change `tailwind.config.js`:
```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,htmx,nim,js}"],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

Next step is create `src/input.css`:
```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

Say tailwind to watch this:
```shell
npx tailwindcss -i ./src/input.css -o ./src/output.css --watch
```

Last step is use `output.css`:
```html
<!DOCTYPE html><html>
  <head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <script src="https://unpkg.com/htmx.org@1.9.6"></script>
    <link href="/dist/output.css" rel="stylesheet">
  </head>
  <body>
    You at {{ title }} page ✨
    <button
      hx-get="https://v2.jokeapi.dev/joke/Any?format=txt&safe-mode"
      hx-target="#output"
      class="text-2xl rounded-md bg-red-400 hover:bg-red-500 active:bg-red-600 duration-300"
    >Click for Joke</button>
  
    <p id="output"></p>
  </body>
</html>
```
