### ISSUE TITLE
Importing freshly imported happyx package can not compile

### ISSUE THREAD

**Issue by PhilippMDoerner** [HapticX/happyx#170]
**Describe the bug** 🐛
After running `nimble install happyx`, trying to import happyx will fail with `/home/philipp/.nimble/pkgs2/happyx-3.0.0-09a3bb3a93ddca05b973235465eb1f2c6414d5b8/happyx/spa/tag.nim(216, 8) Error: undeclared identifier: 're2'`

**To Reproduce** 👨‍🔬

0. (Maybe) Be on Arch Linux with nim 2.0
1. Run `nimble install happyx` or `nimble install happyx@#head` (I tried both)
2. Open a file, write `import happyx`
3. Compile said file with `nim c <yourfile>

**Expected behavior** 🤔
File should compile.

**Screenshots** 🖼
![image](https://github.com/HapticX/happyx/assets/65814317/f92e4964-05c9-4139-9b2e-2d72956f3f31)

**Please complete the following information** 📃
 - OS: Arch Linux
 - OS Version: - Not applicable
 - HappyX version; 3.0.0 (But also occurred with a 2.4.X version)
- Nim version 2.0.0

**Additional context** ✌
I stumbled over this not because I use happyx, but because nimib requires happyx for its docs and I was contributing there. 

https://github.com/pietroppeter/nimib/pull/219#pullrequestreview-1703055739

**Comment by Ethosa** [comment]
delete and update `regex` package to `#head` version
