### ISSUE TITLE
help me please with token authentication

### ISSUE THREAD

**Issue by sjhaleprogrammer** [HapticX/happyx#172]
middleware:

      var headers = req.headers  #how do i parse to json 

      for key,value in pairs(req.headers):
        echo key
        echo value
      

      logger.log(lvlInfo, $headers)
  
    
    
    # auth user
    post "/authenticate[o:UserAuth:json]":

      if dbConn.exists(user.User, "email = ?", o.email.toLowerAscii()):
        var user = newUser()
        dbConn.select(user,"email = ?", o.email.toLowerAscii())

        if not verifyPassword(o.password,user.hash,user.salt):
          return "Invalid email or password."

        {.gcsafe.}:
          var token = sign(o.email,user.role)

      
        return token

      else:
        return "Invalid email or password."

I'm trying to do token authentication is there an easier way to parse a  req.headers (HttpRequest Object) using httpbeast

**Comment by Ethosa** [comment]
Since new commit you can do it:
```nim
var headers = req.headers.toJsonNode()

logger.log(headers)
```

**Comment by sjhaleprogrammer** [comment]
thank you, now I can validate the tokens on routes !
