### ISSUE TITLE
Found Bug 🐛

### ISSUE THREAD

**Issue by sjhaleprogrammer** [HapticX/happyx#173]
Happyx 3.2.0 is failing to build for me :(

**Comment by Ethosa** [comment]
Can you give some additional info? shell output?

**Comment by sjhaleprogrammer** [comment]
![image](https://github.com/HapticX/happyx/assets/60676867/99868294-e769-47ad-afc8-ffb374749c25)
might be related to some conflict with httpbeast and httpcore procs

**Comment by sjhaleprogrammer** [comment]
middleware:

      proc toJsonNode(headers: HttpHeaders): JsonNode =
        result = newJObject()
        for k, v in headers.pairs():
          result[k] = newJString(v)

      var headers = req.headers.toJsonNode()

      proc authorizatize(): bool = 
        var token = headers{"authorization"}.getStr().replace("Bearer ","")
        {.gcsafe.}:
          if verify(token) and decode(token) == "Admin":
            result = true
        
      
      logger.log(lvlInfo, headers)


i wrote my middleware in version 3.0.0 for now but i can't use httpbeast as its in conflict for some reason no logs

**Comment by Ethosa** [comment]
@sjhaleprogrammer please run
```shell
nimble remove happyx -y
nimble install happyx@#head --verbose
```

and show me output

**Comment by Ethosa** [comment]
> might be related to some conflict with httpbeast and httpcore procs

this is strange, because `req.headers` should return `Option[HttpHeaders]` so how it influence to package building ... I have no any idea
https://github.com/dom96/httpbeast/blob/master/src/httpbeast.nim#L489-L492

**Comment by Ethosa** [comment]
Also with `Ubuntu 22.04` this successfully builds
![image](https://github.com/HapticX/happyx/assets/49402667/c8a1458b-1c88-4eef-b35e-be74fd095164)

**Comment by sjhaleprogrammer** [comment]
![image](https://github.com/HapticX/happyx/assets/60676867/64d6807f-0f5b-4645-a8b8-3c3428e1beab)

**Comment by Ethosa** [comment]
```nim
var headers = req.headers.toJsonNode()
```

with `httpbeast` it should to be:

```nim
var headers = req.headers.get().toJsonNode()
```

**Comment by Ethosa** [comment]
@sjhaleprogrammer please show me compile result. It places before `Copying ...` logs

**Comment by sjhaleprogrammer** [comment]
![image](https://github.com/HapticX/happyx/assets/60676867/c7b6a77d-0246-4709-9d4e-86183fbd5e98)

**Comment by Ethosa** [comment]
hm, strange ... are you use `--verbose` flag? what kind of OS are you use?

**Comment by sjhaleprogrammer** [comment]
the last ver that works for me is 3.0.0

**Comment by sjhaleprogrammer** [comment]
im using nixos 23.11

**Comment by sjhaleprogrammer** [comment]
what nim version are you running

**Comment by Ethosa** [comment]
@sjhaleprogrammer I run it at
![image](https://github.com/HapticX/happyx/assets/49402667/b1a16906-c4e1-428b-97a2-96979617f69a)


So ... I changed in `happyx/ssr/utils.nim`:
```nim
## # SSR Utils
## 
import
  json,
  httpcore,
  options


proc toJsonNode*(headers: HttpHeaders | Option[HttpHeaders]): JsonNode =
  result = newJObject()
  when headers is HttpHeaders:
    for k, v in headers.pairs():
      result[k] = newJString(v)
  else:
    for k, v in headers.get().pairs():
      result[k] = newJString(v)


proc toHttpHeaders*(json: JsonNode): HttpHeaders =
  result = newHttpHeaders()
  for k, v in json.pairs():
    result[k] = v.getStr
```

And run this example:
```nim
import happyx

serve "127.0.0.1", 5000:
  middleware:
    var headers = req.headers.toJsonNode()

    proc authorizatize(): bool = 
      var token = headers{"authorization"}.getStr().replace("Bearer ","")
      {.gcsafe.}:
        result = true
    echo headers
```
with 
```shell
nim c -r -d:beast example.nim
```

But it works 🤔

**Comment by sjhaleprogrammer** [comment]
i switched to nim2 and it works i just can't get the .get().tojsonnode to work

![image](https://github.com/HapticX/happyx/assets/60676867/2c5a5990-13f9-41e3-b88b-145802b206f7)

**Comment by sjhaleprogrammer** [comment]
can you commit that or you still working on that i want my code to work or i can't sleep literally lol

**Comment by Ethosa** [comment]
> i switched to nim2 and it works i just can't get the .get().tojsonnode to work

What nim version are you used before?
How do you run server?

**Comment by sjhaleprogrammer** [comment]
i was on nim 1.6 and 3.0.0 was working and i was running it without beast

**Comment by sjhaleprogrammer** [comment]
proc toJsonNode(headers: HttpHeaders): JsonNode =
    result = newJObject()
    for k, v in headers.pairs():
      result[k] = newJString(v)

  var headers = req.headers.toJsonNode()

  proc authorizatize(): bool = 
    var token = headers{"authorization"}.getStr().replace("Bearer ","")
    {.gcsafe.}:
      if verify(token) and decode(token) == "Admin":
        result = true
    
  
  logger.log(lvlInfo, headers) and this was working

**Comment by Ethosa** [comment]
> i was on nim 1.6 and 3.0.0 was working and i was running it without beast

HappyX supports Nim v1.6.14 or above

> can you commit that or you still working on that i want my code to work or i can't sleep literally lol

https://github.com/HapticX/happyx/commit/93bce85e51aeadece397a4a32038e4be54dcfd27

**Comment by sjhaleprogrammer** [comment]
i switched to nim2 and works now so idk what is wrong

**Comment by Ethosa** [comment]
just update HappyX to latest and run your code :)

**Comment by sjhaleprogrammer** [comment]
![image](https://github.com/HapticX/happyx/assets/60676867/e200af70-4a38-40cb-8f55-782005577616)

**Comment by sjhaleprogrammer** [comment]
middleware:

  
      var headers = req.headers.toJsonNode()

      proc authorizatize(): bool = 
        var token = headers{"authorization"}.getStr().replace("Bearer ","")
        {.gcsafe.}:
          if verify(token) and decode(token) == "Admin":
            result = true
        
      
      logger.log(lvlInfo, headers)

**Comment by sjhaleprogrammer** [comment]
something about deepcopy

**Comment by Ethosa** [comment]
are you use something that make copies at `src/webapi.nim(44, 8)`?

**Comment by sjhaleprogrammer** [comment]
Caused by the selectAll function in norm which was working in 3.0.0

**Comment by Ethosa** [comment]
so try to update NORM or use `--deepcopy:on`

**Comment by Ethosa** [comment]
NORM's test cases enables `deepcopy` https://github.com/moigagoo/norm/blob/develop/tests/config.nims#L3

**Comment by sjhaleprogrammer** [comment]
K will give it a try thanks for the help

**Comment by sjhaleprogrammer** [comment]
it works yay !
