### ISSUE TITLE
Found Bug 🐛 statusCode

### ISSUE THREAD

**Issue by sjhaleprogrammer** [HapticX/happyx#174]
# auth user
    post "/authenticate[o:UserAuth:json]":

      if dbConn.exists(user.User, "email = ?", o.email.toLowerAscii()):
        var user = newUser()
        dbConn.select(user,"email = ?", o.email.toLowerAscii())

        if not verifyPassword(o.password,user.hash,user.salt):
          statusCode = 401
          return "Invalid email or password."

        {.gcsafe.}:
          var token = sign(user)

      
        return token

      else:
        statusCode = 401
        return "Invalid email or password."

Am I dumb or statusCode is flat out not working (it returns 200 every time even if not valid )

**Comment by Ethosa** [comment]
So ... I tested these part of code on `Win10` and `Ubuntu 22.04`. All works

```nim

get "/setStatusCode":
    ## Responds "Hello, world!" with 404 HttpCode
    statusCode = 404
    if true:
      if true:
        for i in 0..1:
          if true:
            when true:
              statusCode = 400
    return "Hello, world!"
```
```nim
get "/setStatusCode":
    ## Responds "Hello, world!" with 404 HttpCode
    statusCode = 404
    return "Hello, world!"
```

**Comment by Ethosa** [comment]
Hm, I found this bug, it's very stupid lol
```nim
get "/setStatusCode":
    ## Responds "Hello, world!" with 404 HttpCode
    statusCode = 404
    if true:
      if true:
        for i in 0..1:
          if true:
            when true:
              statusCode = 400
              return 1
    return "Hello, world!"
```

**Comment by Ethosa** [comment]
Reason in `declaredInScope` procedure https://nim-lang.org/docs/system.html#declaredInScope%2Cuntyped
But what can be better analogue?

**Comment by Ethosa** [comment]
I fix it in latest commit ✨

**Comment by sjhaleprogrammer** [comment]
Waytoodank over my head

**Comment by sjhaleprogrammer** [comment]
Thank you

**Comment by sjhaleprogrammer** [comment]
nvm it is still not returning the correct status code same code above i assume it was fixed but I just tested it

**Comment by sjhaleprogrammer** [comment]
im figured it out it was the gcsafe macro i moved it to the top
