### ISSUE TITLE
per-request exception safety and servererror route

### ISSUE THREAD

**Issue by levovix0** [HapticX/happyx#180]
**Is your feature request related to a problem? Please describe.** 🤔
Sometimes, when processing a user request, exceptions may occur on the server. Any exception will kill the entire server, it's very unreliable.

I tried to wrap all routes in
```nim
try:
  ##
except:
  req.answer(
    staticRead("html/server-error.html"),
    headers = newHttpHeaders([("Content-Type", "text/html; charset=utf-8")])
  )
```
but even with this, when i tried to connect to my server with bad internet connection, i got
```
Error: unhandled exception: Connection timed out
```
on server. And server was down.
(it's probably a bug, but it related to idea)

**Describe the solution you'd like** 💡
* Wrap each request inside try/except, log all errors, do not stop server if single request failed.
* Add an `servererror` hook to customize error, that should be sent to client if error occurred. (If this fail, stop server or ignore request, probably should be and option here)

**Comment by Ethosa** [comment]
What you think about new flag `-d:safeRequest`?

I mean that every request will wrapped into `try-except`. In `except` server will respond `500` with error message.
But it will works only with flag `-d:safeRequest`.

This flag can be called differently if you have other suggestions.

**Comment by Ethosa** [comment]
![image](https://github.com/HapticX/happyx/assets/49402667/1268c1ee-57d1-43ce-9540-fb4bcb59f6d0)
![image](https://github.com/HapticX/happyx/assets/49402667/c10e9895-7651-4fe1-9f94-61efbd21be46)
![image](https://github.com/HapticX/happyx/assets/49402667/168691d1-7f94-42f5-afa6-147df9b380a2)

**Comment by Ethosa** [comment]
You can test it since latest commit
