### ISSUE TITLE
Coimponent default field values can be defined in terms of other defaults, but the derived defaults cannot be overriden 🐛

### ISSUE THREAD

**Issue by quimt** [HapticX/happyx#183]
**To Reproduce** 👨‍🔬

```

component withPresets:
  n: int = 5
  s: string = $n
  `template`:
   {self.s}

appRoutes("ROOT"):
  "/":
    tDiv: component withPresets
    tDiv: component withPresets(s= "I better not be 5")



```
**Expected behavior** 🤔
We'd expect to be able to override default field values, however they are written. But in this specific case, the syntax doesn't work.

**
 spa project, chrome browser, happyx@#head

**Comment by Ethosa** [comment]
Solved in the next commit
