### ISSUE TITLE
standard syntax for 'anonymous' components 🔥

### ISSUE THREAD

**Issue by quimt** [HapticX/happyx#184]
Sometimes we just want to create something like a component on the fly, without worrying about its name or derived type beyond that. Karax has a buildHtml that returns VNodes, since everything is a VNode and components are explicitly declared to render to VNodes.

In happyX, `tagRef`s are pretty low-level concepts, and most developers will probably just want to deal with the `Component` type., for simplicity's sake. So it seems like anonymous fragments of code in the DSL should be of type `Component`, which can be set up by taking advantage of the `slot` mechanism.

```
component Container:
  `template`:
    slot

```

This works fine, but an annoying thing for developers is that the name of such an anonymous component must be set and implemented by each development team. Really it feels like the framework should decide on a standard name for such a basic concept. It also seems like the framework should have a final say on how this is implemented, since some additional work with the macros might give a keyword that wouldn't need other hints like 'use' and 'component' to be used along with it.

**Comment by Ethosa** [comment]
Since next commit you can use `buildHtml` for this:
```nim
appRoutes("app"):
  "/issue184":
    var x = buildHtml(tDiv):
      "Hello?"
    buildHtml:
      x
      x
      x:
        "world!"
```
![image](https://github.com/HapticX/happyx/assets/49402667/4df6cfdb-6328-4dc9-ad66-c16ed88a8a66)
