### ISSUE TITLE
slots can't be provided normally when component keyword is omitted 🐛

### ISSUE THREAD

**Issue by quimt** [HapticX/happyx#185]
**To Reproduce** 👨‍🔬
```

component withSlot:
  s: string = $1
  `template`:
   "The number is {self.s}, and the slot is "
   slot

appRoutes("ROOT"):
  "/":
    tDiv:
      component withSlot(): "one"
    tDiv:
      component withSlot($7): "seven"
    tDiv:
      withSlot(): "one"
    #tDiv:
      #withSlot($7): "seven"
    
```
The commented code unfortunately won't compile.

So omitting the component tag works and allows the same syntax, except in this one case. Which will actually be quite common in practice as components start to do all the things that tags do.

**Comment by Ethosa** [comment]
Solved in the next commit
