### ISSUE TITLE
hpx build failled 🐛

### ISSUE THREAD

**Issue by MouriKogorou** [HapticX/happyx#192]
**Describe the bug** 🐛
i created a spa app followed by  spa tutorial in github. but i got an error when i run hpx build command, so what's happened?
it just a template app, no any code written by myself.
![hpx_build_error](https://github.com/HapticX/happyx/assets/43428806/fc367af9-2b80-48aa-8f2c-5da2cafba836)

nim version: 2.0.1
OS Name:                   Microsoft Windows 10  Pro
OS Version:                10.0.19044 N/A Build 19044

**Comment by Ethosa** [comment]
I'll check it soon, now you can test your app via `hpx dev` command
