### ISSUE TITLE
Reactivity example not working

### ISSUE THREAD

**Issue by Ethosa** [HapticX/happyx#213]
### Discussed in https://github.com/HapticX/happyx/discussions/212

<div type='discussions-op-text'>

<sup>Originally posted by **derekdai** December  8, 2023</sup>
I can't get this reactivity example work
```nim
import happyx

var x = remember 0

appRoutes "app":
  "/":
    tDiv:
      "x counter: {x}"
      @click:
        x->inc()
        console.log(x)
```

Although event handler can be triggered by click, the corresponding elements will not be updated. Have I done anything wrong? </div>

**Comment by derekdai** [comment]
Thank you, now it works!
