### ISSUE TITLE
`path` type path params can have default or be optional

### ISSUE THREAD

**Issue by derekdai** [HapticX/happyx#219]
According to [document](https://hapticx.github.io/happyx/happyx#path-params-%F0%9F%9B%A0-validation-%E2%9A%99)
> `path`: like string but includes / chars. Doesn't provides optional and default.

But in fact, HappyX can handle it without problem (checked with `-d:spaDebug`), with one exception `$p:path=/`, this generates incorrect regex (`re2("^/photo-rename([\\S]+)=/$")`), but `{p:path=/}` work as expect.

Currently, if there is a problem with the processing of path parameters, you can only use `-d:spaDebug` or `-d:ssrDebug` to view the generated code to confirm that it matches your expectations. Would it be appropriate to change this to a compile-time error?

**Comment by Ethosa** [comment]
yea, I updated `path` some time ago - #217 
I'll update docs soon

**Comment by derekdai** [comment]
@Ethosa I think this is worth mentioning in the documentation. When specifying a default value for a path path parameter, the value may contain a `/` character, so you must use the `{arg}` syntax instead of `$arg`, according to [this line](https://github.com/HapticX/happyx/blob/106ef2799066816351614b23a402189dd03b0553/src/happyx/routing/routing.nim#L158).

**Comment by Ethosa** [comment]
@derekdai 

I add error throwing when developer tries to use alias for `regex` or `path`. Also I update docs
![image](https://github.com/HapticX/happyx/assets/49402667/e815b380-3505-4a4d-8213-327a19acc918)
