### ISSUE TITLE
Found Bug 🐛 Wrong serve route detected

### ISSUE THREAD

**Issue by dodolboks** [HapticX/happyx#227]
**Describe the bug** 🐛

hi i try new happyx (3.5.2) with nim 2.0.2 and try to connect with mongodb, i follow instruction and try build but error. i thinks it's error from setup route 

/home/dodolboks/riset/catetdulu/src/mondb.nim(7, 6) template/generic instantiation of `serve` from here
/home/dodolboks/riset/catetdulu/src/mondb.nim(22, 5) template/generic instantiation of `routes` from here
/home/dodolboks/.nimble/pkgs2/happyx-3.5.2-4d30fd0b42b2f8c35bf725ecd33df5c741fdb267/happyx/core/exceptions.nim(30, 3) Error: unhandled exception: 
Unhandled exception HpxServeRouteDefect in /home/dodolboks/riset/catetdulu/src/mondb.nim(8, 2)
  Wrong serve route detected  [HpxServeRouteDefect]

Thanks for great work

**Comment by Ethosa** [comment]
Just update HappyX to new version
```shell
nimble remove happyx -y
nimble install happyx@#head -y
```

**Comment by dodolboks** [comment]
thanks it;s work now
