### ISSUE TITLE
how to tell there was json parsing error?

### ISSUE THREAD

**Issue by veksha** [HapticX/happyx#230]
```nim
post "/[task:Task:json]":
  # here `task` variable is initialized even if json parsing error occured
  # also response with an error is automatically sent back!
  # how do i detect that json was not parsed correctly here?
```

thanks for answer.

**Comment by Ethosa** [comment]
It's not possible right now. What exactly do you need? Complete the route after sending the JsonParseError from the server?

**Comment by veksha** [comment]
i need to add task to database, or do not add it if there was an error.

**Comment by Ethosa** [comment]
Ok, I added return statement on any JSON parse error

So, when user sends incorrect JSON, then:
1. Server detects it
2. Server respond error with 400 code
3. Server completes current route without executing

Please, update to latest commit via `nimble install happyx@#head`
