### ISSUE TITLE
 SPA example does not compile 🐛

### ISSUE THREAD

**Issue by array-in-a-matrix** [HapticX/happyx#231]
**Describe the bug** 🐛
The SPA example using routes does not build.

Error:
```txt
An error was occurred when compiling main
stack trace: (most recent call last)
routing.nim(426, 30)     pathParams
routing.nim(317, 16)     pathParamsBoilerplate
exceptions.nim(30, 3)    throwDefect
/home/.../app/src/main.nim(4, 1) template/generic instantiation of `pathParams` from here
/home/.../.local/share/nimble/pkgs/happyx-2.0.0/happyx/core/exceptions.nim(30, 3) Error: unhandled exception:
Unhandled exception HpxPathParamDefect in /home/.../app/src/main.nim(6, 4)
Invalid path param type:
type
int
optional
mutable
default = 100 [HpxPathParamDefect]
```

**To Reproduce** 👨‍🔬
1. create SPA app, `hpx create --kind=SPA --name=app` (with or without tailwindcss)
2. replace `main.nim` with the [SPA example from the documentation](https://hapticx.github.io/happyx/#/guide/path_params):
```nim
import happyx

# declare path params
pathParams:
  paramName:  # assign param name
    type int  # param type
    optional  # param is optional
    mutable  # param is mutable variable
    default = 100  # default param value is 100


appRoutes "app":
  # Use paramName
  "/<paramName>":
    echo paramName
```
3. compile, `hpx dev`.

**Expected behavior** 🤔
Successful compilation  and a development website hosted at localhost.

**Screenshots** 🖼
N/A

**Please complete the following information** 📃
 - OS:  Arch Linux
 - OS Version: Rolling release
 - HappyX version: HappyX 3.7.1
 - HappyX project type: SPA
 
 - Nim version: Tried v2.0.0 and v2.0.2
 - Browser: Firefox
 - Browser Version: 121.0 64-bit (from Arch Linux repositories)

**Additional context** ✌

**Comment by Ethosa** [comment]
Please use this way instead
```nim

# declare path params
pathParams:
  paramNam inte:  # assign param name with `int` type
    optional  # param is optional
    mutable  # param is mutable variable
    default = 100  # default param value is 100
```

I'll fix this in docs

**Comment by array-in-a-matrix** [comment]
Not sure if I should open a new issue as this is somewhat related. 

```nim
import happyx

# declare path params
pathParams:
  paramName int:  # assign param name
    optional  # param is optional
    mutable  # param is mutable variable
    default = 100  # default param value is 100

appRoutes "app":
  "/":
    "hello"
  "/<paramName>":
    {paramName}
    paramName
```

The path `/` works and returns `hello` as expected but trying `/24` or any other value does not work. The browser just loads infinitely.

**Comment by Ethosa** [comment]
How you launch it?
Just `nim js src.nim` or `hpx dev`?

**Comment by Ethosa** [comment]
Started with `hpx dev`
![image](https://github.com/HapticX/happyx/assets/49402667/c78c0104-da8d-4b16-b22b-4dbd0011e2e3)
![image](https://github.com/HapticX/happyx/assets/49402667/cac772f7-09b3-430d-bcb3-067ba727fdac)

**Comment by array-in-a-matrix** [comment]
Oh! You are suppose to keep the `#/`. I was trying `127.0.0.1:5000/35` instead of `127.0.0.1:5000/#/35`.
Thank you for your help! Awesome project!

**Comment by veksha** [comment]
@Ethosa , quick question: why `#/` is needed? can it be removed?

**Comment by Ethosa** [comment]
@veksha `#/` needed only in SPA

**Comment by veksha** [comment]
@Ethosa i see it in SPA, i just don't know why it is there. maybe we can remove i somehow?

**Comment by Ethosa** [comment]
@veksha I think that it can be removed with `History API`, but why?

**Comment by array-in-a-matrix** [comment]
@Ethosa It leads to confusion and makes links longer than necessary.

**Comment by Ethosa** [comment]
@veksha @array-in-a-matrix  Ok, in next commit this possible 
![browser_oDgGdR3Ylh](https://github.com/HapticX/happyx/assets/49402667/98ace702-8120-4b23-88a3-c4b140707fa9)

**Comment by Ethosa** [comment]
Small note: this will possible only with `-d:historyApi`

**Comment by array-in-a-matrix** [comment]
Wow a quick change! Thank you!
