### ISSUE TITLE
calls to proc in template made an unexpected number of times 🐛

### ISSUE THREAD

**Issue by quimt** [HapticX/happyx#232]
**Describe the bug** 🐛
In #229 there was another type of proc call that was not working. I'm making it a separate issue here.

**To Reproduce** 👨‍🔬

**Pay attention** to the use of `counter2` when the `nextCount()` proc is called in the template of `withCounter`. 

```

import happyx, random

component withRandom:
  n: int = rand(99)
  `template`:
    tDiv: "self random: {self.n.val}"
    tDiv: "random in template: {rand(99)}"

var counter: int = 0
var counter2: int = 0
proc nextCounter(c: var int = counter): int =
  c += 1
  result = c

component withCounter:
  count: int = nextCounter()
  `template`:
    tDiv: "self count: {self.count}"
    tDiv(style="background-color: color-mix(in hsl, red 40%, white);"): "count in template: {nextCounter(counter2)}"

component withReps:
  n: int = 5
  `template`:
    for i in 1..self.n.val:
      tDiv(style="border: 0.2em dotted gray;"): slot

appRoutes("ROOT"):
  "/":
    component withReps():
      withCounter()
      withRandom()
      "non-component rand {rand(99)}"
```

**Expected behavior** 🤔
It should be counting 1,2,3 like the other count, since independent counters are being used. But this is not what we see.

**Screenshots** 🖼
![image](https://github.com/HapticX/happyx/assets/126020181/ff0659bc-d154-4ee7-ae87-a239aeeb13f1)

To explore the problem further, if we change the call to nextCount in the template to use a loop, as in:

`
```

component withCounter:
  count: int = nextCounter()
  `template`:
    tDiv: "self count: {self.count}"
    for i in 1..3:
      tDiv(style="background-color: color-mix(in hsl, red 40%, white);"): "count in template: {nextCounter(counter2)}"


```
Then the number of extra counts seems to be the product of the inner and outer loop iterations.

![image](https://github.com/HapticX/happyx/assets/126020181/59c8e759-fccb-42b1-9a93-115cdf7f8cea)

**Please complete the following information** 📃
 version @#head after [d8cb3da](https://github.com/HapticX/happyx/commit/d8cb3da85ae9d4688eb9ad1c4181fc837adefe77)
Manjaro. Chrome

**Comment by Ethosa** [comment]
Seems like reason in rendering

**Comment by Ethosa** [comment]
Solved in the next commit ✌
