### ISSUE TITLE
slot can't be placed in slot of other component in component template 🐛

### ISSUE THREAD

**Issue by quimt** [HapticX/happyx#233]
**Describe the bug** 🐛
When making the template of a component, you can't put the slot in what will become another component's slot.

**To Reproduce** 👨‍🔬

Try:

```

component withReps:
  n: int = 5
  `template`:
    for i in 1..self.n.val:
      tDiv(style="border: 0.2em dotted gray;"): slot

component withRepsSquared:
  n: int = 2
  `template`:
    withReps(2):
      slot

```

**Expected behavior** 🤔
Should run in a well-defined way. The content of the slot of `withRepsSquared` comes from the parent component, so it should become part of the child.

Code actually fails to compile:  `Slots can be used only in components![0m [HpxComponentDefect]
`

**Please complete the following information** 📃
since latest commit to @#head

**Comment by Ethosa** [comment]
Solved in the next commit ✌
