### ISSUE TITLE
handling of ref objects as component fields 🐛

### ISSUE THREAD

**Issue by quimt** [HapticX/happyx#237]
**Describe the bug** 🐛
The fields of ref objects are compiling as null where they weren't before.

**To Reproduce** 👨‍🔬

```

type counterObject* = ref object
  count*: int
  settings*: string

var counterObj1*: counterObject
var counterObj2*: counterObject
proc nextCounter*(c: counterObject): int =
  c.count += 1
  result = c.count

component withCounterObject:
  counter: counterObject = counterObj1
  count: int = nextCounter(counter)
  `template`:
    tDiv: "self count: {self.count}"
    tDiv: "count in template: {nextCounter(counterObj2)}"


appRoutes("ROOT"):
  "/":
    for i in 1..5:
      withCounterObject

```

Code currently compiles but console log indicates that `count` is now null. 

```
 Uncaught TypeError: Cannot read properties of null (reading 'count')
    at nextCounter_2936012847

```
**Expected behavior** 🤔
Code should compile a counter component that can accept different counters to increment.

@#head, [3633cdc](https://github.com/HapticX/happyx/commit/3633cdc9a7990164da5c38454b3c4fb61cb33b0e)

**Comment by Ethosa** [comment]
```nim
var counterObj1*: counterObject = counterObject .new()
var counterObj2*: counterObject = counterObject .new()
```

this works

**Comment by quimt** [comment]
FYI the same code is no longer evaluating the count in the format strings.

![image](https://github.com/HapticX/happyx/assets/126020181/a05326f6-9c42-4285-a6f0-48af7398a14c)

**Comment by quimt** [comment]
As of 294af9aee5d70ff4cb15dfed3c671c9785fac136 the counter shows correctly in html template but the field `count `doesn't increment with each new component.

![image](https://github.com/HapticX/happyx/assets/126020181/316f4809-90b7-49bd-bedb-f87c809122fa)
