### ISSUE TITLE
Iterating over a tuple does not work

### ISSUE THREAD

**Issue by array-in-a-matrix** [HapticX/happyx#238]
**Describe the bug** 🐛

A `for` loop can be used to iterate over a seq or an array but does not work with a tuple.

**To Reproduce** 👨‍🔬
- Create a SPA.
- Use the following code:
```nim
import happyx
appRoutes("app"):
  "/":
    tDiv:
      for i in @["a", "b", "c", "d", "e"]:
        {i} # prints "abcde"
    tDiv:
      for i in [1, 2, 3, 4, 5]:
        {i} # prints "12345"
    tDiv:
      for i in (true, false, true).fields:
        {i} # error
```

Error:
```txt
An error was occurred when compiling main
/tmp/tmp.Pcn3Vfigd7/app/src/main.nim(3, 10) template/generic instantiation of `appRoutes` from here
/tmp/tmp.Pcn3Vfigd7/app/src/main.nim(11, 5) template/generic instantiation of `buildHtml` from here
/usr/lib/nim/core/macros.nim(736, 26) template/generic instantiation of `collect` from here
/usr/lib/nim/pure/sugar.nim(342, 29) Error: expression 'initTag("div", `@`([initTag("true", true, @[], false)]), true)' is of type 'TagRef' and has to be used (or discarded); start of expression here: /usr/lib/nim/core/macros.nim(736, 26)
```

**Expected behavior** 🤔

The expected output should be like the following code:
```nim
for i in (true, false, true).fields:
  echo i
# true
# false
# true
```

**Please complete the following information** 📃
 - OS: [e.g. Win10] Arch Linux
 - OS Version [e.g. 22] Rolling
 - HappyX version [e.g. 2.4.1] (to see it you can use `hpx -v`) HappyX 3.8.0
 - HappyX project type [ssr/spa] SPA
 - Nim version [e.g. 2.0.0] 2.0.2
 - Browser [e.g. chrome] (For SPA projects) Firefox
 - Browser Version [e.g. 22] 121.0.1 (64-bit)

**Additional context** ✌

N/A

**Comment by Ethosa** [comment]
Seems like stdlib bug:
```nim
import sugar

var x = collect(newSeq):
  for i in (true, false, true).fields:
    i
echo x
```

```
Error: expression '(true, false, true)[0]' is of type 'bool' and has to be used (or discarded)
```

**Comment by Ethosa** [comment]
I remove stdlib `sugar.collect` usage in for cycles, so this works now.
