### ISSUE TITLE
hpx create crashes 🐛

### ISSUE THREAD

**Issue by marcusramberg** [HapticX/happyx#24]
**Describe the bug** 🐛
hpx create crashes:

``` sh
❯ hpx create
New HappyX project ...
Project name: syncio.nim(161)          raiseEOF
Error: unhandled exception: EOF reached [EOFError]
```

**To Reproduce** 👨‍🔬
nimble install happyx
$ hpx create

**Expected behavior** 🤔

Asked to input project name

**Comment by Ethosa** [comment]
Where you run this command?

Please, give me more information: OS, OS version, HappyX version

**Comment by marcusramberg** [comment]
> Where you run this command?
> 
> Please, give me more information: OS, OS version, terminal, HappyX version

Hi.
```
# ---=== HappyX CLI ===--- #
                     v0.10.1
```
Tried on arm macos and arm linux.

**Comment by marcusramberg** [comment]
> > Where you run this command?
> > Please, give me more information: OS, OS version, terminal, HappyX version
> 
> Hi.
> 
> ```
> # ---=== HappyX CLI ===--- #
>                      v0.10.1
> ```
> 
> Tried on arm macos and arm linux. - Terminal wezterm.

Tried on x86 linux as well (nixos), same EOF Reached crash.

**Comment by Ethosa** [comment]
@marcusramberg 
Try to update happyx via `nimble install -y happyx@#head` and use

```bash
hpx create --name=ProjName --kind=SPA/SSG
```



> **Describe the bug** 🐛 hpx create crashes:
> 
> ```shell
> ❯ hpx create
> New HappyX project ...
> Project name: syncio.nim(161)          raiseEOF
> Error: unhandled exception: EOF reached [EOFError]
> ```
> 
> **To Reproduce** 👨‍🔬 Steps to reproduce the behavior: nimble install happyx $ hpx create
> 
> **Expected behavior** 🤔
> 
> Asked to input project name

This error throws from stdlib so I just add flags
P.S. But users on win can use command without flags still
