### ISSUE TITLE
components not being generated correctly in slot repetition 🐛

### ISSUE THREAD

**Issue by quimt** [HapticX/happyx#245]
Iteration of slot data is not interacting well with components in the slot.

**To Reproduce** 👨‍🔬
```

import happyx, random, strformat

component Copypasta:
  n: int
  html:
    for i in 1..self.n.val:
      slot

component ShowNum:
  n: int
  html:
    "{self.n.val:04}"

randomize()

appRoutes("ROOT"):
  "/":
    Copypasta(4):
      for i in 1..3:
        let n = rand(9999)
        tDiv: tSpan:
          "{n:04} = "
          ShowNum(n)

```
![image](https://github.com/HapticX/happyx/assets/126020181/ded4f9cc-b1fa-4814-9622-fd4458f4d0d4)
Notice that with the combination of slot repetition and iteration in the slot, the values of the component are only sometimes equal to the values in the route body. Also, `ShowNum` is getting values of n that correlate even though random number generation should have them generated independently.

**Please complete the following information** 📃
HappyX 3.8.12, @#head 
Chrome

**Comment by Ethosa** [comment]
Solved in the next commit 👀
