### ISSUE TITLE
`flags` command 🔥

### ISSUE THREAD

**Issue by Ethosa** [HapticX/happyx#253]
Add `hpx flags` command will be helpful to see all happyx flags instead of going to the docs every time.

Currently, happyx have these flags:

| Flag                 | Description                                                   | Need Value |
| :---:                | :---:                                                       | :--:       |
| `-d:httpx`           | enables Httpx as alternative HTTP Server ⚡                   | ❌         |
| `-d:beast`           | enables HttpBeast as alternative HTTP Server ⚡               | ❌         |
| `-d:micro`           | enables MicroAsyncHttpServer as alternative HTTP Server ⚡    | ❌         |
| `-d:translate`       | enables automatic translate for returns 🌐                     | ❌         |
| `-d:debug`           | enables debug logging 💻                                      | ❌         |
| `-d:oldRenderer`     | enables old renderer for SPA 🍍                               | ❌         |
| `-d:cryptoMethod`    | choose crypto method for `generate_password` methods 🔐       | ✅         |
| `-d:numThreads`      | choose number of threads (httpx/httpbeast) ⌛                 |  ✅        |
| `-d:sessionIdLength` | choose length of session ID ✍                                |  ✅        |
| `-d:disableApiDoc`   | disables built-in API documentation 📕                        | ❌         |
| `-d:disableORM`      | disables built-in ORM 📑                                      | ❌         |
| `-d:appName`         | choose name of application (SSR/SSG) 📕                       | ✅         |
| `-d:apiDocsPath`     | choose path for API documentation 📕                          |  ✅        |
| `-d:noliveviews`     | Disables LiveViews at SSR/SSG (It helpful for components) 📕  |  ❌        |
| `-d:safeRequests`    | Enables requests safety (On error returns 500 with err msg) 📕|  ❌        |
| `-d:disableDefDeco`  | Disables default decorators (`AuthBasic`, `GetUserAgent`) 👀  |  ❌        |

## Dev Consts 👨‍💻
| Flag                      | Description                                                | Need Value |
| :---:                     | :---:                                                      | :--:       |
| `-d:compDebug`            | enables debug logging for components                       | ❌         |
| `-d:compTreeDebug`        | enables debug logging for components (tree mode)           | ❌         |
| `-d:ssrDebug`             | enables debug logging for SSR                              | ❌         |
| `-d:spaDebug`             | enables debug logging for SPA                              | ❌         |
| `-d:reqModelDebug`        | enables debug logging for request models                   | ❌         |
| `-d:routingDebug`         | enables debug logging for routing                          | ❌         |
| `-d:componentDebugTarget` | after this component program will terminated               | ✅         |
| `-d:reqModelDebugTarget`  | after this request model program will terminated           | ✅         |

**Comment by Ethosa** [comment]
Now on `dev` branch:
![image](https://github.com/HapticX/happyx/assets/49402667/4c75859c-2370-4911-b5e8-3f975a4bbd0e)

**Comment by Ethosa** [comment]
Updated command:
![image](https://github.com/HapticX/happyx/assets/49402667/a868d0cb-ec08-4c8a-9a8f-f9c8f42014a8)

**Comment by Beetroit** [comment]
how to disable opening browser automatically when i run `hpx dev --reload`

**Comment by Ethosa** [comment]
> how to disable opening browser automatically when i run `hpx dev --reload`

it's not possible at now. I think we can remove browser opening in the future.
