### ISSUE TITLE
Exception thrown on invalid value for Enum in model

### ISSUE THREAD

**Issue by bluemax75** [HapticX/happyx#254]
An exception is thrown when an incorrect value is received for an enum parameter in a model. Don't know how to handle the exception

This code throws an exception when the POST is sent with an incorrect value in 'k'
```
import happyx

type
  Kind = enum
    circle
    square

model Obj:
  k: Kind
  st: string

serve("127.0.0.1", 5000):
  post "/[data:Obj:json]":
    echo data
    return ""
```

This is run with:
* happyx-3.9.0
* Nim devel
* OS: Archlinux

**Comment by Ethosa** [comment]
In the next commit on `dev` branch new route type will be added:

```nim
import happyx

type
  Kind = enum
    circle
    square

model Obj:
  k: Kind
  st: string

serve("127.0.0.1", 5000):
  post "/[data:Obj:json]":
    echo data
    return ""
  onException:
    # here built-in variables:
    # `url`, `body` is string
    # `e` is `ref Exception`
    echo "URL: ", url
    echo "BODY: ", body
    echo "EXCEPTION: [", e.name, "] - ", e.msg
```


## Examples
Input is:
```http
POST / HTTP/1.1
Host: localhost:5000
Content-Type: application/json
Cache-Control: no-cache

{"k": "circl1e", "st": "hello"}
```
Output is:
```
URL: /
BODY: {"k": "circl1e", "st": "hello"}
EXCEPTION: [ValueError] - Invalid enum value: circl1e
```

Input is:
```http
POST / HTTP/1.1
Host: localhost:5000
Content-Type: application/json
Cache-Control: no-cache

{"k": "circl1e", "st":
```
Output is:
```
URL: /
BODY: {"k": "circl1e", "st":
EXCEPTION: [JsonParsingError] - input(1, 22) Error: { expected
```

**Comment by bluemax75** [comment]
Using the current dev branch I get the following error at compile time:

> /home/charly/tmp/nim/rest/MetrotelAPI/happyx/src/happyx/spa/components.nim(1039, 18) Error: > undeclared identifier: 'initTagVm'
> candidates (edit distance, scope distance); see '--spellSuggest':
>  (2, 5): 'initTag'

I'm not sure if I'm using the dev branch correctly. I cloned the repo in the same directory as the example program, checked out the dev branch and imported with

``` Nim
import ./happyx/src/happyx
```

**Comment by Ethosa** [comment]
@bluemax75, this error was solved in the last commit on `dev` 👀

**Comment by bluemax75** [comment]
Great. After updating the new endpoint onException is working
Thank you very much. Excellent work you are doing

**Comment by bluemax75** [comment]
I'm afraid that onException is not using the value of statusCode
If I try to return 422 error code with the following code:

```Nim
import ./happyx/src/happyx

type
  Kind = enum
    circle
    square

model Obj:
  k: Kind
  st: string

serve("127.0.0.1", 5000):
  post "/[data:Obj:json]":
    echo data
    return ""

  onException:
    echo "Exception"
    echo e.name
    echo e.msg
    statusCode = 422
    return "Exception"
```

I get a 200 Ok response code

**Comment by Ethosa** [comment]
@bluemax75, now the `onException` statement is included in your routes, so the problem has been solved 👀 (no code changes needed)

**Comment by bluemax75** [comment]
I can confirm that it is working now. Thank you!
