### ISSUE TITLE
Components Life Cycle

### ISSUE THREAD

**Issue by Ethosa** [HapticX/happyx#26]
Example:
- [x] create - call only one time at page loaded
- [x] beforeUpdate- call before every rerender
- [x] update - call every rerender
- [x] exit - call only one time at page exit

**Comment by horanchikk** [comment]
Maybe "scriptng" and "styling" should be in "render"?

**Comment by Ethosa** [comment]
@horanchikk can you give me more ideas?

**Comment by horanchikk** [comment]
> @horanchikk can you give me more ideas?

на парах завтра подумаем, спать хочу уже <3
