### ISSUE TITLE
Form-Data: Boundary string not cut off completely 🐛

### ISSUE THREAD

**Issue by svbalogh** [HapticX/happyx#286]
**Describe the bug** 🐛
The auto-generated boundary string is not cut off completely from the request body string when I use  
```
parseFormData(req.body)
```
**To Reproduce** 👨‍🔬
1. create file to send to the server, e.g. example.txt with the following content: "some input file, e.g. a certificate"
2. implement a post route using happyx
3. send the file using a multipart/form-data body ( I use postman to send the request)
4. On the server side, parse the request body with the happyx function parseFormData(req.body)
5. print the parsed form data or write it to a file
6. observe the file

**Expected output** 🤔
console output or file content: 
```
"some input file, e.g. a certificate"
```
**Actual output**
```
"some input file, e.g. a certificate"
----------------------
```
**Additional info**
The complete boundary string generated by postman is the following:
```
----------------------------196777003309965867532698
```
So apparently happy x does cut off something, but not the whole boundary string.

 - OS: FreeBSD 13.1
 - Nim compiler 2.0
 - HappyX: head
 - Project type: ssr
 - HTTP Server default

**Edit:** I realized that the two trailing dashes after the boundary string of the last form-data element mark the end of the whole multi-part form data, so I removed it from the initial question. The main problem, as explained above, remains, though.

**Comment by Ethosa** [comment]
can you provide example code?

**Comment by svbalogh** [comment]
Sure, here is an example how I use it. I call myProc in a post route, like so:
```
  serve "0.0.0.0", 8042:
    post "/myRoute":
      {.gcsafe.}:
        let response = myProc(req)
        echo req.headers
        echo req.body
        statusCode = response.statusCode
        return response.body
```

This is the implementation of the called function:
```
proc myProc(req: Request): RestResponse =
    let (strTblRef, tblRef) = parseFormData(req.body)
    let tmpDir = createTempDir("somePrefix", "someSuffix")
    for k, v in tblRef.pairs:
      if k == "setId" or k == "parameters":                                      # just skip for now...
        echo v  
        continue
      echo v
      writeFile(tmpDir / v.filename, v.data) 
  return RestResponse(statusCode: 200, body: %*{})
```

Echo output (Header):

```
{"postman-token": @["b44c7202-8ecd-36db-ac1c-4ea32bb8f013"], "accept": @["*/*"], "content-length": @["553"], "content-type": @["multipart/form-data; boundary=--------------------------452314762052999410888566"], "host": @["0.0.0.0:8042"], "connection": @["keep-alive"], "user-agent": @["PostmanRuntime/7.39.0"], "accept-encoding": @["gzip", "deflate", "br"]}
```

Echo output (Body):
```
----------------------------452314762052999410888566
Content-Disposition: form-data; name="setId"

"SomeSetId"
----------------------------452314762052999410888566
Content-Disposition: form-data; name="parameters"

{
  "a": 1,
  "b": 2,
  "c": "test",
  "d": {
    "x": 1,
    "y": "test"
  }
}
----------------------------452314762052999410888566
Content-Disposition: form-data; name="cert"; filename="cert.pem"
Content-Type: application/x-x509-ca-cert

"some input file, e.g. a certificate"
----------------------------452314762052999410888566--
```
Echo output (v):
```
(data: "\r\nsome input file, e.g. a certificate\r\n----------------------\r\n", filename: "cert.pem", contentType: "application/x-x509-ca-cert", name: "cert")
(data: "{\n  \"a\": 1,\n  \"b\": 2,\n  \"c\": \"test\",\n  \"d\": {\n    \"x\": 1,\n    \"y\": \"test\"\n  }\n}\r\n----------------------", filename: "", contentType: "", name: "parameters")
(data: "TODO\r\n----------------------", filename: "", contentType: "", name: "setId")
some input file, e.g. a certificate
----------------------
```

I hope this helps, if you need anything else from me, let me know. Thanks in advance for your help!

**Comment by svbalogh** [comment]
Proposed a fix: https://github.com/HapticX/happyx/pull/288/commits
