### ISSUE TITLE
set buildHtml root attrs to "display: contents;"

### ISSUE THREAD

**Issue by quimt** [HapticX/happyx#295]
**Is your feature request related to a problem? Please describe.** 🤔
One kind of undocumented syntax with buildHtml is that the content sit in a div. This makes the built html content different from the literal content of the DSLs body in a couple of significant ways. First, it imposes mandatory line breaks pretty much all the time. Second, it disrupts parent-child relationships between tags.

**Describe the solution you'd like** 💡
"display: contents;"  is the CSS setting made to get around this and is designed with computer-generated html in mind where divs might be written without any semantic intent. While it may be nice to have the content enclosed in a div automatically in some circumstances, it's much harder to opt-out of being in a div once it is baked in to `buildHtml `and `buildHtmlProcedure.` It seems like a div with "display: contents" would change the existing code minimally while making it easier to reason about and use [build/thunk]Html data.

**Comment by Ethosa** [comment]
Solved in the next commit via deleting unnecessary `div` elements.
![image](https://github.com/HapticX/happyx/assets/49402667/56ba6f67-9f97-488c-890d-6bf4cf8fd8ef)

![image](https://github.com/HapticX/happyx/assets/49402667/e3fc701e-95a9-4dc5-bcee-07473122452e)
