### ISSUE TITLE
OSError on hpx dev 🐛

### ISSUE THREAD

**Issue by joshuajohncohen** [HapticX/happyx#30]
**Describe the bug** 🐛
Whenever I run `hpx dev` on my SPA project it gives this error:
oserr.nim(95)                   raiseOSError
Error: unhandled exception: No such file or directory
Additional info: nim [OSError]
Shutdown ...

**To Reproduce** 👨‍🔬
1. Create a new SPA project with `hpx create`
2. `cd` into the created folder
3. Run `hpx dev`
4. Observe the error

**Expected behavior** 🤔
That `hpx dev` would run my code

**Screenshots** 🖼
![image](https://github.com/HapticX/happyx/assets/65085812/8c8eeccb-2db6-4ecf-8a1b-957aaebb84aa)

**Desktop (please complete the following information):** 💻
 - OS: MacOS
 - Browser: N/A
 - Version: 0.17.0

**Additional context** ✌
I have also been able to replicate this issue with the base https://Replit.com template ChooseNim and installing happyx.

**Comment by Ethosa** [comment]
Please update HappyX
Actual version is `0.18.2`

**Comment by joshuajohncohen** [comment]
On nimble the latest version is 0.17.0. Do I have to install @HEAD?

**Comment by Ethosa** [comment]
> Do I have to install @Head?

@joshuajohncohen, you can just run current command and get latest version 🙂
```bash
nimble install -y happyx@#head
```

**Comment by Ethosa** [comment]
@joshuajohncohen are you still experiencing an error?
