### ISSUE TITLE
thunk-component interaction in loops 🐛

### ISSUE THREAD

**Issue by quimt** [HapticX/happyx#303]
**Describe the bug** 🐛
As we move into the world of TagRef-generating functions, there are some issues with placing them directly in the SPA DSL. Specifically components in thunks seem to get copied in loops even though they aren't in other types of loops.

**To Reproduce** 👨‍🔬
```

var counter: int = 0
proc nextCount(): int =
  counter += 1
  result = counter

component ShowNextCount:
  count: int = nextCount()
  html:
    {self.count}

proc countFactory(): TagRef = buildHtml:
  {nextCount()}

proc countComponentFactory(): TagRef = buildHtml:
  ShowNextCount

appRoutes("ROOT"):
  "/":
    "counts as thunks:"
    for i in 1..5:
      tDiv: countFactory()
    "counts as components in thunks:"
    nim: counter = 0
    for i in 1..5:
      tDiv: countComponentFactory()
    "counts with just the components"
    nim: counter = 0
    for i in 1..5:
      tDiv: ShowNextCount
```

**Expected behavior** 🤔
All counts go from 1 to 5.  

**Screenshots** 🖼
But we actually only see this when components and thunks are not interacting.
![image](https://github.com/HapticX/happyx/assets/126020181/ad107111-817e-4fad-bc04-00786f9a5cfa)

**Please complete the following information** 📃
 current head version

**Comment by Ethosa** [comment]
Unfortunately, what you expect to receive is impossible.
This happens because when you call a function, you do not pass any additional information to create a new component, so all 5 components are one.
![image](https://github.com/HapticX/happyx/assets/49402667/cab4b516-18c3-41b7-8fac-86add69d95fe)

**Comment by quimt** [comment]
`because when you call a function, you do not pass any additional information to create a new component, so all 5 components are one`

But _I_ don't pass any additional information to create a new component when looping, so all components in a loop should be one by the same logic. They were, until changes to the DSL were made so that it adds that information, if I recall.

I was anticipating that a similar change to the DSL could keep track of which loop the function call should be going in, and create new components accordingly.

Is there a reason related to the AST that makes handling the repeated loops much easier than handling the repeated function calls?

**Comment by Ethosa** [comment]
I managed to fix the situation by introducing a global variable responsible for the loop.

**Comment by quimt** [comment]
Sounds interesting. I will have a look at how Karax handles it because I'm curious. They have thunks for the dom and vdom but I haven't investigated the mechanics of how/if they work.

**Comment by quimt** [comment]
I've noticed with the recent patch that there are some undesirable side effects. [Nimib](https://github.com/pietroppeter/nimib)'s and [NimiSlides](https://github.com/HugoGranstrom/nimiSlides)' functionality for embedding HappyX code no longer works. Meanwhile in some of the moderately complex components using TagRef-generating procs in loops within component 'hml', there seem to be new problems with rendering as the browser complains that the call stack size has exceeded the limit.
