### ISSUE TITLE
query string not updated in liveview example 🐛

### ISSUE THREAD

**Issue by mirco-ackermann** [HapticX/happyx#322]
**Describe the bug** 🐛
In liveview the query string does not update

**To Reproduce** 👨‍🔬
1. Start the testc12.nim example
2. Open http://localhost:5000/search?q=1
3. Note that it shows "You search: 1" as expected
4.  Open http://localhost:5000/search?q=2
5.  It still shows "You search: 1"

**Expected behavior** 🤔
I would expect the displayed value to change when the query parameter is changed.

**Environment**
HappyX 4.4.1
Nim 2.1.9 [Linux: amd64]
opensuse Tumbleweed
Firefox 127.0.2

**Comment by mirco-ackermann** [comment]
I did a bit of digging by adding 
```nim
echo toStrLit result
```
to the end of the route macro. The cause is probably that the initial `query` is captured by the proc closure and then gets saved to the `liveviewRoutes["search"]` table.  That is cached and reused when the page is freshly loaded. Here is the relevant section of generated code:
```nim
      elif `==`(urlPath, "/search"):
        {.gcsafe.}:
          if not(hasKey(liveviewRoutes, "/search")):
            liveviewRoutes["/search"] = proc (): TagRef =
              buildHtml:
                head:
                  tTitle:
                    "HappyX Application"
                body:
                  tDiv(id = "app"):
                    let q = decodeUrl(query ? q)
                    tP:
                      "You search: {q}"
                  tDiv(id = "scripts")
          let _html = liveviewRoutes["/search"]()
```

**Comment by Ethosa** [comment]
Solved in the next commit

**Comment by mirco-ackermann** [comment]
Nice, that was fast.

I think there might be a regression at the `http://localhost:5000/liveviews-upgrade` endpoint in the same `testc12.nim`. With the commit `55157dd9385454d07ab94e72c6a25d70e97f40a3` I get a `Exception message: key not found: /liveviews-upgrade` exception when pressing the "click me!" button in the webbrowser.

Here is the traceback I get:
```
[2024-07-29 at 08:51:02]:INFO Server started at http://127.0.0.1:5000
[2024-07-29 at 08:51:05]:INFO GET::/liveviews-upgrade
[2024-07-29 at 08:51:05]:INFO GET::/liveviews-upgrade
set counter to 1, but before it be 0
key not found: /liveviews-upgrade
Async traceback:
  /home/mirco/happyx/tests/testc12.nim(70) testc12
  /home/mirco/happyx/src/happyx/ssr/server.nim(189) main
  /home/mirco/.choosenim/toolchains/nim-2.0.8/lib/pure/asyncdispatch.nim(2022) waitFor
  /home/mirco/.choosenim/toolchains/nim-2.0.8/lib/pure/asyncdispatch.nim(1711) poll
  /home/mirco/.choosenim/toolchains/nim-2.0.8/lib/pure/asyncdispatch.nim(1452) runOnce
  /home/mirco/.choosenim/toolchains/nim-2.0.8/lib/system/threadimpl.nim(269) processPendingCallbacks
  /home/mirco/happyx/src/happyx/ssr/liveviews/liveviews.nim(84) handleRequest (Async)
  /home/mirco/happyx/tests/testc12.nim(58) :anonymous
  /home/mirco/happyx/src/happyx/spa/renderer.nim(206) rerender
  /home/mirco/.choosenim/toolchains/nim-2.0.8/lib/pure/collections/tables.nim(879) []
  /home/mirco/.choosenim/toolchains/nim-2.0.8/lib/pure/collections/tables.nim(247) []
  /home/mirco/.choosenim/toolchains/nim-2.0.8/lib/pure/collections/tables.nim(235) raiseKeyError
Exception message: key not found: /liveviews-upgrade
```

**Comment by Ethosa** [comment]
Please try latest commit in the `dev` branch

**Comment by mirco-ackermann** [comment]
I think I am on the dev branch, git says I've got `origin/dev` and have the commit  `00affed9ae326edf5a285e25451a6118aae91680`  from Mon Jul 29 15:12:32 2024 +0700.

**Comment by Ethosa** [comment]
@mirco-ackermann try latest commit again :)

**Comment by mirco-ackermann** [comment]
Just tried it, now it works :-)
