### ISSUE TITLE
Spurious divs without style as "display: contents;" 🐛

### ISSUE THREAD

**Issue by quimt** [HapticX/happyx#324]
**Describe the bug** 🐛
In #295 discussion seemed to conclude that the enclosing div would be removed from `buildHtml`. It seems to be back in the current commit.

**To Reproduce** 👨‍🔬
```

component Hello:
  html:
    tDiv:
      "hello"

let b = buildHtml:
  Hello

let c = buildHtml:
  tDiv:
    "hello"

appRoutes("ROOT"):
  "/":
    tDiv: {$b}
    tDiv: {$c}

```

![image](https://github.com/user-attachments/assets/3ac99a60-101d-42fc-8820-a3c2adb65bcd)

**Comment by Ethosa** [comment]
Hmm, seems like a just new found bug, because it works with `buildHtmls`, not with `buildHtml` 👀

**Comment by Ethosa** [comment]
`buildHtml` always returns all children as a onlye one element - `div` with `onlyChildren: true`, so:
```nim
buildHtml:
  tDiv:
    {$c}
    c
```

return this:
![image](https://github.com/user-attachments/assets/81cc9b97-7945-4403-9ecd-1690b25621e0)
