### ISSUE TITLE
Found Bug 🐛 SSR example not working

### ISSUE THREAD

**Issue by AxelRHD** [HapticX/happyx#328]
**Describe the bug** 🐛
I followed the documentation to generate a SSR application, got an error while running.

**To Reproduce** 👨‍🔬
1. Install HappyX with `nimble install happyx@#head`
2. Create project with `hpx create --name happyx_playground --kind SSR`
3. Run project with `hpx dev --reload`
4. See the following error:
```shell
An error was occurred when compiling main
/home/axelr/nim-projects/happyx_playground/src/main.nim(12, 17) template/generic instantiation of `renderTemplate` from here
/home/axelr/nim-projects/happyx_playground/src/main.nim(6, 16) template/generic instantiation of `compileTemplateFile` from here
/home/axelr/.asdf/installs/nim/2.0.8/nimble/pkgs2/nimja-0.9.0-f6f818530160503c175357621ac39fef14028b8b/nimja/sharedhelper.nim(9, 15) Error: cannot open file: /home/axelr/.asdf/installs/nim/2.0.8/nimble/pkgs2/happyx-4.4.3-77cb6eb83dc30cefcacd64a70d7d9349506a481b/happyx/tmpl_engine/templates/index.html
```

**Expected behavior** 🤔
See a running example.

**Screenshots** 🖼

**Please complete the following information** 📃
 - OS: Ubuntu
 - OS Version 22
 - HappyX version 4.4.3
 - HappyX ssr
 
 - HappyX project language Nim
 - Nim/Python version 2.0.8
 - HTTP Server Default

**Comment by Ethosa** [comment]
@AxelRHD please delete `nimja 0.9.0` and install `nimja 0.8.7`.
