### ISSUE TITLE
Write More Docs 📕

### ISSUE THREAD

**Issue by Ethosa** [HapticX/happyx#37]
- [x] Mounting 🔌
- [x] CORS ⚙
- [x] Request Models 🔨
- [ ] SPA tutorial 📕
- [x] SSG tutorial 📕
- [ ] Style Guide 🎴

May be anyone want to help me? 👀

**Comment by horanchikk** [comment]
так напиши че иссуе создаешь

**Comment by Ethosa** [comment]
Add mounting, CORS and request models in https://github.com/HapticX/happyx/commit/a4840d392f689f9ca3e3aa416d9325378b025a5b
