### ISSUE TITLE
Found Bug 🐛

### ISSUE THREAD

**Issue by Beetroit** [HapticX/happyx#375]
**Describe the bug** 🐛
`hpx dev` for SSR on wsl fails because it can't start the default browser correctly. 

**To Reproduce** 👨‍🔬
1. Create an SSR app `hpx create --name:calculator --kind:SSR`
2. Run the app `hpx dev --reload `
3. The server starts and launches the default browser which fails to run correctly.

**Expected behavior** 🤔
Starting a browser instance should be optional via cmd flags

**Screenshots** 🖼
![image](https://github.com/user-attachments/assets/8afb9746-75d3-4432-ae13-0954b69d6ffd)
Here the server starts and starts the browser

![image](https://github.com/user-attachments/assets/163cc774-7370-4e84-b13d-d92cfed4ac8f)
Here's the browser page, it spins like this and does nothing. My local machine (the windows host) also cannot access the page, but it works fine if i use `nim c -r src/main.nim`

![image](https://github.com/user-attachments/assets/cf7b47eb-509c-40fd-a010-d6fd17318551)
Here you see, killing the browser, makes the server exit.

### EDIT: I just found out that the hpx server doesn't actually exit, it crashes, but remains active as a background process.
https://drive.google.com/file/d/1L2husefbp3-icFTBYeBMkt_kO1uG_o3V/view?usp=sharing
Here's a video showing the bug in action. 

**Please complete the following information** 📃
 - OS: WIN 11 PRO 23H2 + WSL 2 ( Ubuntu 22.04)
 - OS Version [e.g. 22]
 - HappyX version 4.6.4
 - HappyX project type [ssr/spa]
 
 - HappyX project language = Nim
 - Nim version  = 2.2.0
 - HTTP Server Default

**Comment by Ethosa** [comment]
`hpx dev` command works only for `SPA` at now
