### ISSUE TITLE
New Feature 🔥 Add scalar doc 

### ISSUE THREAD

**Issue by Beetroit** [HapticX/happyx#376]
**Is your feature request related to a problem? Please describe.** 🤔
Swagger UI provides none of the advanced functionalities that scalar does, like editing cookies, multiple request body types and customizing headers.

**Describe the solution you'd like** 💡
I would like for scalar ui to be added to the documentation options, kind of like Quart did. 

**Describe alternatives you've considered** 💁‍♀️
Swagger UI lacks a lot of features.
Redoc is not interactive.

**Additional context** ✌
Following the format in `{HAPPYX_INSTALL_PATH}/happyx/ssr/docs/open_api.nim`
Here's the html template.
```
"/docs/scalar" -> get:
  req.answerHtml("""<head>
  <title>HappyX x Scalar</title>
  <style>
    body {
      margin: 0;
    }
  </style>
</head>
<body>
  <script id="api-reference" data-url="/docs/openapi.json"></script>
  <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
</body>
""")
```
The url was taken from Quart-Schema's implementation. 
Adding this feature will make Happyx more dev friendly, especially for devs building out APIs.
Here's what scalar and swagger UI looks like for the example calculator app

### Scalar UI
![image](https://github.com/user-attachments/assets/dd786b4f-af05-488f-aa92-d2c80ccf1ce3)

### Swagger UI (doesn't even show request body)
![image](https://github.com/user-attachments/assets/ff35a56b-926b-4c29-9312-e7977ce8f258)

**Comment by Beetroit** [comment]
For scalar ui, i imported the openapi.json directly from the happyx app, so no change is required.

**Comment by Ethosa** [comment]
Nice idea! btw, happyx has a `redoc` and builtin documentation)

try these url's in your api:

```
/docs/redoc
/docs
```

**Comment by Beetroit** [comment]
Yep, I've checked out both. The default UI is very beautiful, and eye catching, would've been a lot more useful if it was interactive. But I see you have a lot on your hands already.

Hence the scalar. Do check it out. It'd help drive more interest as well.
