### ISSUE TITLE
How do query params work?

### ISSUE THREAD

**Issue by Beetroit** [HapticX/happyx#378]
I've been trying to get query params to work for a while now. But i've had no luck. I'm building out an api server as a way to learn how to use happyx ssr and norm for api development.
Here's what my code looks like:
![image](https://github.com/user-attachments/assets/ba34dc78-b507-475c-93b7-b10b48046ea4)
And here's the terminal output.
![image](https://github.com/user-attachments/assets/855948df-5c91-4cc9-9234-224fb1931948)

I'm unable to access the id variable. 
Here's an image of the scalar ui and the network logs tab. The request goes through fine, but i can't access the variable. 

![image](https://github.com/user-attachments/assets/5831070b-a3f8-44d0-9941-d04667eccedb)

It also isn't showing up in the query object as you can see below (i'm using a middleware to print the urlPath and query)
![image](https://github.com/user-attachments/assets/61ce1c51-7493-45b6-bef2-62eede807a82)

Example code will be appreciated. Also, if i can get it to show up in the docs, that'll be nice. I'm aware of `/get/{id:int}` but query params have always been part of my coding style and i'm not comfortable switching to path params.
Thanks.

**Comment by Ethosa** [comment]
Query works at the latest happyx version 🤔
```nim
get "/get":
  echo query  # StringTableRef
  echo urlPath  # string
  echo query?id  # string
  return query?id
```

so this working: http://localhost:5000/get?id=123
![image](https://github.com/user-attachments/assets/9903a74c-c7dd-40dc-b2c8-6bc9a2247d6d)
![image](https://github.com/user-attachments/assets/8d10770f-1732-4167-a66a-e17f308c0f85)

**Comment by Ethosa** [comment]
try to reinstall happyx
```shell
nimble remove happyx -y
nimble install happyx@#head
```

**Comment by Beetroit** [comment]
Here's are screenshots
Micro
![Screenshot 2024-11-26 130441](https://github.com/user-attachments/assets/6dacd165-eb68-4751-a738-5cf553e67e6d)

httpx
![Screenshot 2024-11-26 130351](https://github.com/user-attachments/assets/6ae730b9-544f-451a-bc78-500f97aa86e7)

httpbeast
![Screenshot 2024-11-26 130247](https://github.com/user-attachments/assets/f435baa5-8731-49ea-a982-b45d19bc04de)

default server
![Screenshot 2024-11-26 130113](https://github.com/user-attachments/assets/bdf23f52-7685-4ace-bcc3-4c48e29816ea)

As you can see it doesn't get the query params on httpx or httpbeast.
