### ISSUE TITLE
Found Bug 🐛: Auth and Cached decorators not working with Mounts

### ISSUE THREAD

**Issue by Beetroit** [HapticX/happyx#383]
**Describe the bug** 🐛
I use a mount in my api, the code is defined in another file and then mounted. When i try to use either of the new auth decorators, or the new cached one, i get a weird error. It happens whether i'm using the decorator in the mount but not from the main server file.

**To Reproduce** 👨‍🔬
1. Create a basic ssr server
2. Add some code in another file (so you can mount it)
3. Try to use AuthBearerJWT, AuthJWT, or the Cached decorators on a route inside the mount file. 

**Expected behavior** 🤔
Mounts should work fine with the new decorators.

**Screenshots** 🖼
![image](https://github.com/user-attachments/assets/af353825-6ebb-45c3-837e-e56ed00e192b)

![image](https://github.com/user-attachments/assets/5718afd1-2776-4956-bd6d-c562618e1c58)
This is from the mount file.

**Please complete the following information** 📃
 - OS: WIN 11 PRO 23H2 + WSL 2 ( Ubuntu 22.04)
 - HappyX version 4.7.0
 - HappyX project type [ssr/spa]

 
 - HappyX project language = Nim
 - Nim version  = 2.2.0
 - HTTP Server Default (also fails on others too, tested on httpx and httpbeast)

**Comment by Ethosa** [comment]
@Beetroit can you provide some example of code?

**Comment by Beetroit** [comment]
# main.nim file
```
import happyx
import test_case

serve "127.0.0.1", 5000:
    onException:
        echo e.msg
        echo e.name
        return {"error": getCurrentExceptionMsg()}
    
    notFound:
        return {"response": "Not found"}

    get "/":
        "Hello, World!"

    mount "/users" -> User
```

# test_case.nim file
```
import happyx

mount User:
    get "/":
        return {"response": "Hello, World!"}

    @Cached(10)
    get "/testcache":
        return {"response": "Cache"}
```

# nim.cfg
```
verbosity=0
hints=off
define = release
define = ssl
threads = on
deepcopy=on
define=beast
```

**Comment by Beetroit** [comment]
nope
