### ISSUE TITLE
Add asAttachment argument to answerFile proc

### ISSUE THREAD

**Issue by MCRusher** [HapticX/happyx#41]
**Is your feature request related to a problem? Please describe.** 🤔
I want to be able to download the file sent using answerFile instead of displaying it inline, and to do that you can add `("Content-Disposition", "attachment")` to the http headers, but answerFile does not expose its HttpHeaders

**Describe the solution you'd like** 💡
allow some way of allowing files to be sent as attachments instead of inline

**Describe alternatives you've considered** 💁‍♀️
Could alternatively allow passing an HttpHeaders argument like answer accepts and then append the content type if it doesn't exist or something.

**Comment by MCRusher** [comment]
If changes that amount to the below are acceptable I can fork and submit a PR myself if you want, this is currently what I'm using to allow this functionality

```nim
proc answerFile*(req: Request, filename: string, code: HttpCode = Http200, asAttachment = false) {.async.} =
...
var headers = @[("Content-Type", fmt"{contentType}; charset=utf-8")]
if asAttachment:
  headers.add(("Content-Disposition", "attachment"))
req.answer(content, headers = newHttpHeaders(headers))
```

**Comment by MCRusher** [comment]
Or alternatively:

```nim
...
let headers = [
  ("Content-Type", fmt"{contentType}; charset=utf-8"),
  ("Content-Disposition", "attachment")
]
let httpHeaders = if asAttachment:
  newHttpHeaders(headers)
else:
  newHttpHeaders(headers[0..0])
req.answer(content, headers = httpHeaders)
```

**Comment by Ethosa** [comment]
> If changes that amount to the below are acceptable I can fork and submit a PR myself if you want, this is currently what I'm using to allow this functionality
> 
> ```nim
> proc answerFile*(req: Request, filename: string, code: HttpCode = Http200, asAttachment = false) {.async.} =
> ...
> var headers = @[("Content-Type", fmt"{contentType}; charset=utf-8")]
> if asAttachment:
>   headers.add(("Content-Disposition", "attachment"))
> req.answer(content, headers = newHttpHeaders(headers))
> ```

@MCRusher  Send PR please if it's not too much trouble for you 🙂
