### ISSUE TITLE
Fixed UNIX path bug 🐛

### ISSUE THREAD

**Issue by Mr-Thack** [HapticX/happyx#47]
**Describe the bug** 🐛
The hpx program fails to read path and thus is unable to run nim for compilation.

**To Reproduce** 👨‍🔬
1) Use a UNIX machine
2) attempt ``hpx build`` on examples/todo

**Expected behavior** 🤔
No crashes

**Desktop (please complete the following information):** 💻
 - OS: Arch Linux

**Additional context** ✌
🥱

**Comment by Mr-Thack** [comment]
GitHub won't let me make a pull request because I didn't fork it properly. 🙈
Be back soon... ✌️

**Comment by Ethosa** [comment]
Solved in https://github.com/HapticX/happyx/commit/dd4402499a5e18a471d784d314ce91525a043315

Thx @Mr-Thack
