### ISSUE TITLE
how HappyX faster than httpbeast on web frameworks benchmark?

### ISSUE THREAD

**Issue by bung87** [HapticX/happyx#52]
https://web-frameworks-benchmark.netlify.app/result?l=nim. 

just found it became top of nim web frameworks at this round. from bottom to top. just wondering why

**Comment by Ethosa** [comment]
yeap, and is not only in Nim 🙂
However, this benchmark uses the simplest tests
![image](https://github.com/HapticX/happyx/assets/49402667/ae41393f-a082-4e97-bf9d-2db18ce62905)

**Comment by bung87** [comment]
maybe get benefit from router ?
