### ISSUE TITLE
raw / verbatim / literals

### ISSUE THREAD

**Issue by quimt** [HapticX/happyx#55]
**Is your feature request related to a problem? Please describe.** 🤔

It's frustrating to always have strings piped through the various macro layers  such as strformat. On the frontend, it's still going to be better sometimes to pass or accept data from external JS scripts that communicate with literal strings. 

**Describe the solution you'd like** 💡
An equivalent idiom of Karax's verbatim, for direct injection of HTML->Dom would be nice.
In line with the idea of taking care of things under the hood, it would also be good to recognize the raw string literal types `nnkStrLit..nnkTripleStrLit` from nim and never apply strformat to them.

**Describe alternatives you've considered** 💁‍♀️
text tags from karax are acceptable for me since I use code snippets, but the more macro intensive approach here seems to want to be more aggressive about minimizing keystrokes along with boilerplate

**Additional context** ✌

I don't know how much you've tried to squeeze out of Karax in its current state, but here are the idioms for JS scripts that I'm familiar with in the buildHtml environment there:

```
script(): text """
  var params = {"appName": "graphing", "width": 800, "showTaskbar": true}
  var myApp = new App(params,true)
  myApp.inject("myID")
  """
```
Note that since JS is untyped, there can be some strange datatypes that are hard to exchange between nim and js. This means that some things from external libraries are better off implemented as pure JS commands, especially in an initial testing phase that needs to be quick. Another natural use case is talking about the literal syntax of code, which is one thing that one would naturally want to do on websites:

```
text """to properly template the string with the right user id and score, you type:"""
tdiv(class="code"):
  text """ Your score is {{ fmt{score,0.2d} }}"""
```

There are many uses for a verbatim as well. One that I am familiar with is inputting mathematics. MathML is excessively verbose, so inputting latex is better. But both MathJax and katex (in auto-render mode) fight with Karax' control of the DOM at present and shut down Karax' reactivity. So the next best bet is to bind katex ability to render string to mathML and then inject it into the DOM verbatim

```
proc renderToStringKatex(s:kstring): kstring {.importjs: "katex.renderToString(@)" .}
proc renderKatex(s:kstring): VNode = buildHtml:
  verbatim(renderToStringKatex(s))
```

Then build from there to interpolation of strings with inline latex.  Note that this is considerable effort compared with having Katex' auto-render work correctly out of the box. One thing that your approach with routing on the front end seems to help with is giving a little bit more leeway to other reactive scripts while still getting its own job done!

 Using routes on the front-end DSL should help a lot for writing code in a common source file while effectively managing user experience and computational resources.

**Comment by Ethosa** [comment]
> I don't know how much you've tried to squeeze out of Karax in its current state, but here are the idioms for JS scripts that I'm familiar with in the buildHtml environment there:

In HappyX you can use it with this way:
```nim
tScript( ... ):
  """
  some JS code here
  """
```

**Comment by Ethosa** [comment]
> An equivalent idiom of Karax's verbatim, for direct injection of HTML->Dom would be nice.
In line with the idea of taking care of things under the hood, it would also be good to recognize the raw string literal types nnkStrLit..nnkTripleStrLit from nim and never apply strformat to them.

You mean that `fmt` for all raw strings is a bad practice?

**Comment by Ethosa** [comment]
I think that can add compile-time flag `-d:strformat` or something like this.

Flag will enable `fmt` for all raw strings

**Comment by quimt** [comment]
> > An equivalent idiom of Karax's verbatim, for direct injection of HTML->Dom would be nice.
> > In line with the idea of taking care of things under the hood, it would also be good to recognize the raw string literal types nnkStrLit..nnkTripleStrLit from nim and never apply strformat to them.
> 
> You mean that `fmt` for all raw strings is a bad practice?

Yes, given the need to apply other functions to strings. The reason why fmt was not automatically implemented in base nim is pretty much the same reason why people should be able to opt out of it here..

What I was suggesting , given that applying fmt automatically to _most_ strings is a convenience, was to maybe make it apply only to single-quoted 'typical' strings, but not to triple-quoted literals and such types that coders usually meant to be taken literally.

**Comment by quimt** [comment]
> I think that can add compile-time flag `-d:strformat` or something like this.
> 
> Flag will enable `fmt` for all raw strings

I think that tags might be better than flags, given that you have capacity to label textTags. It maybe helpful to think about what  a tiered approach would look like, giving sensible defaults but allowing the programmer to override when writing specific components or interfacing with specific external scripts.

1.  **(automatically)** single quoted strings get fmt, but triple quoted don't.
2.  **(manual override)** provide tags (or maybe a proc/template/macro)  that allow the programmer that they mean to override the default behavior. But for literal strings, the programmer can just use fmt manually, and for single quoted strings, the user can usually just switch to literals, so I'm not sure that this tier would be useful.

**Comment by Ethosa** [comment]
triple/single quoted realization sounds good 👀

**Comment by Ethosa** [comment]
@quimt here is example
https://github.com/HapticX/happyx/blob/master/tests/testjs9.nim#L26-L28

**Comment by Ethosa** [comment]
1. auto string formatting
2. raw string
3. handle raw string
![image](https://github.com/HapticX/happyx/assets/49402667/27c1b732-1a47-435e-a1ca-91bfcdcb104a)

**Comment by Ethosa** [comment]
BTW you can easily edit JS code in script with [HappyX extension](https://marketplace.visualstudio.com/items?itemName=HapticX.happyx&ssr=false) 🙂
![image](https://github.com/HapticX/happyx/assets/49402667/f8f1bb22-6ddb-4dec-9f3f-951bb31a0d48)

**Comment by quimt** [comment]
Looks good!

So we have

1. A convention for entering literal strings that fits with Nim's style (effectively we have declared only that 'standard' strings have a little bit more processing done to them, other than recognizing whitespace chars like '\n' and using the escape character.
2.  A way to enter JS scripts in the SPA DSL


This leaves:
3. A way to get the DSL to enter raw HTML code,, Karax does this with a `verbatim` kind of [tag](https://github.com/karaxnim/karax/blob/7cc88e905120f9d9b2c680d7622e49a6bf4514f2/karax/karax.nim#L169C27-L169C27). This is useful for pretty much the same reasons why we'd want to be able to use raw JS code. Sometimes, when an external library has a limited API or we are just trying to follow their documentation with plain HTML examples, it's simplest to just copy and paste raw html or to use the raw html that the library gives to us.  Precisely because many JS libraries on the front end are so preoccupied with string manipulation, we should expect many cases where  they want to provide us with  verbatim strings of html with html tags and attributes.

Looking at how text tags are implemented in HappyX, I'm not sure exactly how you want to do this.  An isVerbatim flag would be in keeping with what the library already has. Another option would be to implement something like the [html2karax](https://github.com/nim-lang-cn/html2karax/) utility as a macro. Over the long term, this could have benefits for documentation.

**Comment by Ethosa** [comment]
@quimt I add a new command into CLI - `hpx html2tag FILENAME`

it converts HTML code into `buildHtml` macro in new file `source.nim` (or other file with flag `--output`

CLI work result
Command: `hpx html2tag source`
| `source.html` | `source.nim` |
| :---: | :---: |
| ![image](https://github.com/HapticX/happyx/assets/49402667/ecefcb15-5886-45c5-b6af-ccf7c545d68c) | ![image](https://github.com/HapticX/happyx/assets/49402667/d10ab073-43e8-42f9-87e9-cecf251733fe) |

**Comment by Ethosa** [comment]
This command available since v1.8.0 (future release at this moment)

**Comment by Ethosa** [comment]
Here is example of raw HTML usage
![image](https://github.com/HapticX/happyx/assets/49402667/509b0567-c64d-4b59-8d34-ba599388d3e7)

**Comment by Ethosa** [comment]
https://github.com/HapticX/happyx/commit/de6eef6881e5c3e948dc7ddd601c995bcff59983
