### ISSUE TITLE
stateful components should have easily manipulable internal state🔥

### ISSUE THREAD

**Issue by quimt** [HapticX/happyx#60]
**Is your feature request related to a problem? Please describe.** 🤔
Component manipulation is limited. If components are objects, the meaning of the component tag should be to place any component into the document, no matter how it is produced or identified. One can declare a component that modifies its own state by referencing itself.

```
   component HelloWorld:
    y : int = 17

    `template`:
      tDiv:
        "Hello, world {self.y}!"
      tButton:
        "change world"
        @click:
          self.y += 1

```
However, one cannot even bind a component to an identifier and then add it to the document by the identifier. If we say
`  var hw = initHelloWorld("hw", y=88)`
then 
`hw` will fail to render anything, and 'component hw' will fail because the renderer currently assumes that we need to initialize a new component whenever we use the `component` tag.

**Describe the solution you'd like** 💡

1. `component hw` should render to the document in the same way ` component HelloWorld(y=88)` would. 
 ![image](https://github.com/HapticX/happyx/assets/126020181/b0301b3d-223e-4fb0-9dd6-a37b2296e67b)
 
2. In line with the goal of having methods and other things that modify component fields, any other changes required for the normal features of object declaration and field access to work should be implemented. I note, for example that one cannot declare [exported fields](https://nim-by-example.github.io/types/objects/) with `*`

**Describe alternatives you've considered** 💁‍♀️
Since text gets rendered just by placing the text node, it might be argued that the component tag should not exist at all and that the macro should just render any statement that results in a component in the same way. However I don't think its likely to be worth the change in the documented API

One can wrap components in some other datatype that houses the state which can be publicly modified, but this would be a needless addition of a new type that the programmer needs to juggle. stateful components are the only datatype that the programmer will really want to deal with.

**Comment by Ethosa** [comment]
How about
```nim
component MyComponent:
  ....

...

var myComp = useComponent(MyComponent)

...

buildHtml:
  component MyComponent
  component myComp
```

This will available in new HappyX version

**Comment by Ethosa** [comment]
I think that this is better way
```nim
var myComp = use component MyComponent

buildHtml:
  component MyComponent
  component myComp
```

This also will work with
```nim
var myPathParam = use pathParam arg

"/some/<myPathParam>"
```

**Comment by quimt** [comment]
> I think that this is better

Sounds good! If the syntax of 'use' there were flexible enough to allow for a singleton component to render in many places, that might be even better. I think it would be only marginally more useful to the programmer, though, so may not be worth the effort.

Question: how would you intend to initialize components.? Currently MyComponent acts as a proc in the DSL and is initialized as `MyComponent(myVal=0)`, but in the global environment of nim `MyComponent (<stuff>)` is a constructor and requires `:`, so outside the buildHtml environment, it looks like we can currently only go
`var myComp = MyComponent(myVal : 0)`
or
`var myComp = initMyComponent("required identifying string", myVal = 0)`

I assume `use` will be some kind of macro that allows us to use the normal syntax of the component tag, like
`var myComp = use component MyComponent(myVal = 0)`?

If that is so it looks like` initMyComponent()`, if it persists internally, should be made private if possible. It seems like the intent of the library is rapidly becoming that users of the library should never have to  call this function.

**Comment by Ethosa** [comment]
> I assume use will be some kind of macro that allows us to use the normal syntax of the component tag, like
var myComp = use component MyComponent(myVal = 0)?

Yeap, you're right 🙂

> If that is so it looks like initMyComponent(), if it persists internally, should be made private if possible. It seems like the intent of the library is rapidly becoming that users of the library should never have to call this function.

Nope, it impossible, because all component use it in `buildHtml`

**Comment by Ethosa** [comment]
![image](https://github.com/HapticX/happyx/assets/49402667/fcb9c4df-a09e-4c35-ac98-c432b336aee3)

**Comment by Ethosa** [comment]
Only this usage is allowed
![image](https://github.com/HapticX/happyx/assets/49402667/c728e358-5d49-4417-ab6f-9f6b623ec146)


Because it translates into:
![image](https://github.com/HapticX/happyx/assets/49402667/f7011bd7-4395-4f30-af26-b1d1e0ae73e8)
```nim
var myComp = use(component Button):
  "This is button in component"
```

**Comment by quimt** [comment]
So 
```
var myComp = use component MyComponent(myParam=3):
  "this text is a field of the component?"

```
should translate to
```
var myComp = use(component MyComponent(MyParam=3)):
  "this text is a field of the component?"
```
I ask because in a buildHtml environment, eventually stuff in a block form gets interpreted as a child tag in the html document. For instance, coming from Karax, MyParam is an argument to the proc, while the text would be interpreted as a child VNode. There, it makes it hard to use other 'body' macros inside the DSL and leads to a syntactic difference between using a macro or proc inside the DSL vs in global scope.

**Comment by Ethosa** [comment]
I mean that syntax
```nim
var x = use component Comp(...):
  ...
```
is impossible, because Nim translates it into 
```nim
var x = use(component Comp(...)):
  ...
```

Solution is
```nim
# this
var x = use(component Comp(...):
  ...
)
# or this
var y = use:
  component Comp(...):
    ...
```

**Comment by Ethosa** [comment]
Upd usage syntax for variables:

```nim
buildHtml:
  component Component(...)
  component `comp`
```

**Comment by Ethosa** [comment]
here is usage example
![image](https://github.com/HapticX/happyx/assets/49402667/bf4c7da3-546b-464c-b355-ab0bfc37cb64)

**Comment by Ethosa** [comment]
And here result

![image](https://github.com/HapticX/happyx/assets/49402667/c1713b3c-aaba-4785-9b80-21c141cabbbf)

**Comment by Ethosa** [comment]
Final version:
![image](https://github.com/HapticX/happyx/assets/49402667/db1d0c77-b369-44c4-93aa-55282c9cfad2)

P.S.:
`Button.action` is `State[proc(): void]`

**Comment by Ethosa** [comment]
Solved in https://github.com/HapticX/happyx/commit/02f65ccb913e4523595d57e1d2b3867a6114c427

**Comment by quimt** [comment]
Ah, subtle! I think this is what I was trying to get at. The programmer can want either the 'wrong' or 'right' translation depending on the situation, it seems, but it's certainly good to know which one you are going to get!

> is impossible, because Nim translates it into
> 
> ```nim
> var x = use(component Comp(...)):
>   ...
> ```
> 
> Solution is
> 
> ```nim
> # this
> var x = use(component Comp(...):
>   ...
> )
