### ISSUE TITLE
Found Bug 🐛

### ISSUE THREAD

**Issue by quimt** [HapticX/happyx#62]
**Describe the bug** 🐛
Component updating creates multiple instances of static content.

**To Reproduce** 👨‍🔬
Stick with

```
  component HelloWorld:
    y: int = 17

    `template`:
      tDiv:
        "Hello, world {self.y}!"
      tButton:
        "change world"
        @click:
          self.y += 1
```
  
  Then place component in app and run. Click the button to update the parameter. The component button gets duplicated , though the message itself is replaced normally.

![image](https://github.com/HapticX/happyx/assets/126020181/325f2ed0-2724-4b2c-abdb-6e344d297ed1)

Before latest commit to 1.9.0, it worked normally.
**Desktop (please complete the following information):** 💻
 - OS: [linux x64]
 - Browser [chrome version 113]

**Comment by Ethosa** [comment]
So ...
1. This bug works only in components
2. This bug works with old renderer also

**Comment by Ethosa** [comment]
I think that bug in component renderer

**Comment by Ethosa** [comment]
Current solution is write `root` tag in component:
![image](https://github.com/HapticX/happyx/assets/49402667/517a480c-658e-44c7-a7a0-cdbbc750e346)
![image](https://github.com/HapticX/happyx/assets/49402667/9732a35a-652d-46cf-b470-e890257724e7)
![image](https://github.com/HapticX/happyx/assets/49402667/1a5662ac-7af2-48ad-bb16-7a82643df976)

I fix bug in next release `v1.9.1`

**Comment by quimt** [comment]
Sounds good. Works for me.

**Comment by Ethosa** [comment]
Now you can write without `root` tag

**Comment by Ethosa** [comment]
Currently, I solved same problem (only one component tag was updated before)
![image](https://github.com/HapticX/happyx/assets/49402667/8bd11e0c-7a4a-47f9-a35a-031238df44f7)
