### ISSUE TITLE
Improve website 🔥

### ISSUE THREAD

**Issue by Ethosa** [HapticX/happyx#70]
Describe these things ❔
- [x] Why HappyX is necessary;
- [x] HappyX goals;
- [x] HappyX contacts;
- [x] HappyX code examples (slider).

Improve these things ✨
- [x] Design.

Add more pages 👨‍🔬
- [x] Sponsors;
- [x] Roadmap;
- [x] Guide;
- [x] Language bindings.

Add translations 📖:
- [x] Russian;
- [x] Japanese;
- [x] French;
- [x] Chinese;
- [x] Korean.

**Comment by Ethosa** [comment]
Add RoadMap in f366c8a

**Comment by Ethosa** [comment]
language bindings was described in user guide

**Comment by horanchikk** [comment]
@Ethosa Check #114, language support has been added there
