### ISSUE TITLE
Component Constructors🔥

### ISSUE THREAD

**Issue by quimt** [HapticX/happyx#79]
**Is your feature request related to a problem? Please describe.** 🤔
It's currently possible to overload the init procs , which is useful. However, the syntax leaves a bit to be desired.

1.  The init proc is not used in the examples, so users need to look into the source to learn the signature of the proc.
2.  Nim doesn't have much in the way of conventions for Object Oriented code, so the programmer will not know to search for a  proc that begins with 'init'  to learn about it.
3.  The syntax is fussy: `proc initMyComp(uniqCompId: string, n: int)` can be used in the SPA as `component MyComp(n=3)` but  `proc initMyComp(s: string, n: int)`  cannot.

**Describe the solution you'd like** 💡
Some kind of constructor block inside the component declaration seems best, although it would be nice if there were a way to use something like it in the global environment as well.

Something like `constructor proc (<args>): <returnType> = <body>` inside the declaration and  `constructor proc  <component>(<args>): <returnType> = <body>` in the global envrionment might be nice. Here I'd suggest keeping the proc keyword to reduce ambiguity and keep the macro relatively simple and legible. The goal is to inject `uniqCompID: string` into the args, to name the internally used proc correctly, and to implicitly use the correct result type.

**Describe alternatives you've considered** 💁‍♀️
It might make sense if the programmer used the init proc all the time so that `component X` would read instead in examples as `component initX`. But this would make the component 'tag' redundant, require significant refactoring, and is contrary to the style of the framework.

**Comment by Ethosa** [comment]
Please, describe reason to overloading component constructor.

I don't understand how this may be useful, because you can:

```nim
component MyComp:
  a: int = 0
  b: float = 10.0
  c: string = ""
  d: seq[bool] = @[true]

...

buildHtml:
  component MyComp(a = 10, c = "Hello!")
  component MyComp(b = 1.0, d = @[])
```

**Comment by quimt** [comment]
One can declare procs with a bunch of situationally useful parameters too. It can still be useful to overload them.

There are situations where a parameter is used to generate the component, but it is not part of the component's state. Further, I might want some restrictions in how the component is constructed. I'm thinking about a lot of procs that exist to give parts of the document correct html formatting. Since the header is supposed to format strings, not arbitrary html code, this is what fundamentally makes sense for header fields

```
component FancySectionHeader:
  s:string
  ...
  <formatting options>
  ...
...
```

Then `component FancySectionHeader(s="foo")` can make sense, and `component FancySectionHeader(n = 3)` can too, because this type of component has a specific expectation about how ints should be represented as strings.  But `component FancySectionHeader(s="foo", n=3)` might not make sense, since these are conflicting inputs that specify different ideas about what the header's contents should be. Further, there may be  `(FancySectionHeader(tracker:stateTracker = ...,)` where the stateTracker is an object from external scope that FancySectionHeader doesn't own, and is hence inappropriate to have as part of the component itself.

As with overloading procs in general, this is not so much about it being impossible to do things without overloading. 
It's about trying to write simpler code where the code itself naturally documents its own use cases and the dependencies between them.

**Comment by Ethosa** [comment]
I can make `constructor` statement for components, ex:

```nim
component MyComponent:
  sum: int
  constructor(a: int, b: int):
    self.sum = a + b
  constructor():
    self.sum = 0
```

so here two ways:
1. Allow only declared constructors
2. Allow both declared constructors and default constructor for ALL fields

**Comment by quimt** [comment]
Way 2 is best. I think the goal of happyx is to hide the subtly different syntax of nim's default constructor, which uses the `ExprColonExpr` node as opposed to normal proc arguments. Having a default constructor is of course great!

100% of the time we define a component, we will want to construct it, and 80% of the components that we define will be constructed in a standard way, without worrying about the kind of complexity that might make us want to overload.

**Comment by Ethosa** [comment]
In custom constructor params developers can't use component fields, ex:

## Wrong
```nim
component A:
  a: int
  constructor(a: int)
```

## Right
```nim
component A:
  a: int
  constructor(b: int)
```

**Comment by Ethosa** [comment]
To avoid confusion component constructor usage will be
```nim:
component MyComponent->construct(args)
```

**Comment by Ethosa** [comment]
Final version:

## Declaration
![image](https://github.com/HapticX/happyx/assets/49402667/8b1ea6fd-54af-4d50-b352-159532a6a624)

## Usage
![image](https://github.com/HapticX/happyx/assets/49402667/eac0de2a-f972-487e-b90e-a86d8b174222)

## Result
![image](https://github.com/HapticX/happyx/assets/49402667/74a1526d-2bc3-4734-bf5d-43780c4e1e47)

**Comment by Ethosa** [comment]
Thanks to your contribution! 🙂

**Comment by quimt** [comment]
>To avoid confusion component constructor usage will be
>
>`component  MyComponent->construct(args)`

Just to be clear, what confusion are you trying to eliminate? That only the default constructor can give component field names as parameter identifiers?

**Comment by Ethosa** [comment]
> what confusion are you trying to eliminate?

now here is no confusion.

**Comment by quimt** [comment]
I ask because there is always some inherent confusion when there is a shift in syntax.

It is confusing to go around saying
```
component Normal(n=4)
component Usual(s ="super message")
component Regular(m = 5, f = changeSuperState)
```
then have to use

```
Regular->construct(initSeed=4)
```

If proc--like syntax for Regular() works in the first case, it's potentially confusing that it suddenly doesn't in the second case. It's also potentially confusing for readers of source code who are trying to learn: why is there this big difference in syntax when we are doing essentially the same kind of thing (creating and attaching a component) from a high-level point of view ?

**Comment by Ethosa** [comment]
> If proc--like syntax for Regular() works in the first case, it's potentially confusing that it suddenly doesn't in the second case. It's also potentially confusing for readers of source code who are trying to learn: why is there this big difference in syntax when we are doing essentially the same kind of thing (creating and attaching a component) from a high-level point of view ?

When developer use:
- constructor, happyx calls proc `constructor_COMPONENTNAME` with some args.
- default constructor (that automatically declared when component declared), happyx calls proc `initCOMPONENTNAME` with some args

so

```nim
component SomeComponent:
  a: int = 0  # optional field
  b: int = 2  # optional field

  constructor():
    self.a = 10
    self.b = 10

  constructor(value: int):
    self.a = value
    self.b = value

var html = buildHtml:
  component SomeComponent(1, 2)  # a = 1, b = 2
  component SomeComponent->construct()  # a = 10, b = 10
  component SomeComponent->construct(100)  # a = 100, b = 100
```

**Comment by quimt** [comment]
>    constructor, happyx calls proc constructor_COMPONENTNAME with some args.
>    default constructor (that automatically declared when component declared), happyx calls proc initCOMPONENTNAME    with some args


But if I'm using the DSL's API as a developer, I don't particularly care about the different ways in which the implemented is coded for defaults vs custom constructors. I just want it to work, and to minimize the effort involved in writing and refactoring SPA code.

>
>default constructor (that automatically declared when component declared), 
>

So if the default constructor is automatically declared when my component is declared, why can't the alternative constructors also be automatically declared as an override of proc initCOMPONENTNAME? I'm not saying that they should, because there are some reasons why you'd want a distinction in lower level code, but there would be the benefit of having the syntax be the same both at the low-level implementation and the language of the DSL

Even if there is a distinction at the low-level, though, I'm not sure I want to code with it in the DSL. It will tend to make maintaining code needlessly complex. Imagine switching between using the default constructor and a user-developed constructor, over and over, which will happen many times while developing different components. Now I need to spend extra time  typing or deleting the  `->construct` and extra effort staying aware of all the details of the component implementation whenever I make the change -- I need to know what the fields are in order to know if I have to use the `->construct` or not
