### ISSUE TITLE
Happyx parses HTML comments  🐛

### ISSUE THREAD

**Issue by array-in-a-matrix** [HapticX/happyx#90]
**Describe the bug** 🐛
Happyx parses HTML comments, if variable does not exist compilation fails, if variable does exist it's corresponding content is substituted. 

**To Reproduce** 👨‍🔬
1. Setup new happyx project (I used SSR with templates).
2. Open the `index.html` and change the variable being called to something that does not exist (e.g. `{{ title }}`  -> `{{ bug }}` ).
3. Comment that variable out (`<!-- <title>{{ bug }}</title> -->`).
4. Compile.

**Expected behavior** 🤔
Compiler should completely ignore variables that are commented regardless if they exist or not.

**Screenshots** 🖼
N/A

**Desktop (please complete the following information):** 💻
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 115.0.3 (64-bit)

**Additional context** ✌
N/A

**Comment by Ethosa** [comment]
It's bug in `nimja`. At this moment I can't to do something.

In future I add own template engine
