### ISSUE TITLE
Bash cursor freeze after hpx --help

### ISSUE THREAD

**Issue by not-lum** [HapticX/happyx#92]
**Describe the bug** 🐛
```bash
hpx --help
```
Output:
```
Usage:
  mainCommand [optional-params] 
Options:
  -h, --help                  print this cligen-erated help
  --help-syntax               advanced: prepend,plurals,..
  -v, --version  bool  false  set version
cligen.nim(569)          parser
Error: unhandled exception:  [HelpOnly]
```
And then the bash cursor freezes 

**To Reproduce** 👨‍🔬
```bash
hpx --help
```
or
```bash
hpx -h
```
**Expected behavior** 🤔
No bash cursor freeze 

**Screenshots** 🖼
https://youtu.be/5FPLwLxKApo

**Desktop (please complete the following information):** 💻
 - OS: Fedora Linux (bash)
 - Browser: -
 - Version: -
 - HappyX version: 1.11.0
 - HappyX project type: -

**Comment by Ethosa** [comment]
![image](https://github.com/HapticX/happyx/assets/49402667/fc39d048-8552-442b-b712-43adc5384b6f)
use `hpx help` instead of `hpx --help`

**Comment by not-lum** [comment]
This didn't help. It still freezes

**Comment by Ethosa** [comment]
hmm ... maybe it has something to do with illwill 🤔

**Comment by not-lum** [comment]
Your commit fixed this, but the issue still applies for `hpx update` (and probably for some other `hpx <do_somthing>` commands)

**Comment by Gruruya** [comment]
It seems Illwill doesn't use [addExitProc](https://nim-lang.org/docs/exitprocs.html) for some reason, but that's what I would do.

**Comment by not-lum** [comment]
Now the following error appears after `hpx help`:
```
illwill.nim(788)         checkInit
Error: unhandled exception: Illwill not initialised [IllwillError]
```
