### ISSUE TITLE
`hpx build` takes forever 🐛

### ISSUE THREAD

**Issue by not-lum** [HapticX/happyx#93]
**Describe the bug** 🐛
Tried to build examples/website and examples/nimlang via `hpx build`. Still waiting for `Compiling main script ... ` to complete (it's been about 30 minutes already)

**To Reproduce** 👨‍🔬
1. `cd examples/nimlang` or `cd examples/website`
2. `hpx build`
3. Wait

**Expected behavior** 🤔
Compile faster?

**Desktop (please complete the following information):** 💻
 - OS: Fedora Linux 38
 - Browser: -
 - Version: -
 - HappyX version: 1.11.0
 - HappyX project type: SPA

**Comment by Ethosa** [comment]
Try to update HappyX to `#head`
