### ISSUE TITLE
Allow websocket and html route on same path

### ISSUE THREAD

**Issue by Gruruya** [HapticX/happyx#96]
A `ws "path":` route should be allowed next to a `"path":` route and be differentiated based on if the request's headers have websocket upgrade headers (Connection: upgrade, Upgrade: websocket).

**Comment by Ethosa** [comment]
I'll solve this issue in the next commit.

Now, you should first declare `ws path` and then `path`.
![image](https://github.com/HapticX/happyx/assets/49402667/54e731b5-abb1-4200-bd5a-392fc631bbcc)
