### ISSUE TITLE
component fields only accept concrete type (like `seq[T]`) 🐛

### ISSUE THREAD

**Issue by quimt** [HapticX/happyx#99]
**To Reproduce** 👨‍🔬

```
  component ToDo:
    messages: seq[string]
    `template`:
      tDiv:
        for i in messages.items:
          "{i} "

```
 ```Error: 'seq' is not a concrete type```

**Expected behavior** 🤔
I'd normally expect to be able to do declare all types of things to be fields of the component. Preliminary investigation on my part suggests that this behavior might be due to runtime declaration of the component, but I'm not sure.

It's worth noting that for now, the issue seems to be easy to work around for those who already understand it, since declaring the component with a default seq  allows successful functionality. This works, for example:
```
  component ToDo:
    messages: seq[string] = @["yello","goodbye"]
    `template`:
      tDiv:
        for i in self.messages.items:
          "{i} "

  appRoutes("ROOT"):
    "/":
      component ToDo(messages = @["wavy", "shavy"])

```

**Comment by Ethosa** [comment]
I found reason

| ![image](https://github.com/HapticX/happyx/assets/49402667/b9295806-4db9-4be5-a3b4-076db9a36b31) | ![image](https://github.com/HapticX/happyx/assets/49402667/70ccc6cf-72a5-4d56-bcfa-f03f00de6246) |
| :---: | :---: |

**Comment by Ethosa** [comment]
This will solved in the next commit
